[package]
name = "seiran-pdf"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
image.workspace = true
krilla.workspace = true
krilla-svg.workspace = true
miette.workspace = true
read-fonts.workspace = true
seiran-compiler.workspace = true
thiserror.workspace = true
tracing.workspace = true
usvg.workspace = true

[dev-dependencies]
lopdf.workspace = true
tempfile.workspace = true
toml.workspace = true

[lints]
workspace = true
