version: 2
updates:
  - package-ecosystem: "github-actions"
    # update GitHub Actions dependencies weekly
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    # update Rust dependencies weekly
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "rust"
    allow:
      - dependency-type: "all"
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
