[workspace]
members = [
  "crates/cli",
  "crates/font",
  "crates/parser",
  "crates/pdf_gen",
  "crates/read_config_file",
  "crates/seiran",
  "crates/text",
  "crates/types",
]
resolver = "3"

[workspace.metadata]
default-run = "app"

[workspace.package]
authors = ["Kuma"]
description = "Seiran is a tool to generate PDF files from text files."
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Kumasan00/seiran"
version = "0.1.0"

[workspace.dependencies]
allsorts = "0.16.1"
anyhow = { version = "1.0.100", features = ["backtrace", "std"] }
ariadne = "0.1.1"
clap = { version = "4.5.53", features = ["derive"] }
harfbuzz_rs = "2.0.1"
harfrust = "0.4.1"
indexmap = "2.12.1"
lazy-regex = "3.4.2"
memchr = "2.7.6"
memmap2 = "0.9.9"
miette = { version = "7.6.0", features = ["fancy"] }
pdf-writer = "0.14.0"
rayon = "1.11.0"
read-fonts = "0.36.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.10"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["local-time"] }
ttf-parser = "0.25.1"

[workspace.lints.clippy]
needless_return = "allow"

[profile.release]
debug = false
lto = true
opt-level = 3
strip = "symbols"
