[workspace]
members = [
  "crates/app",
  "crates/cli",
  "crates/font",
  "crates/pdf_gen",
  "crates/read_file",
  "crates/stypes",
  "crates/text",
]
resolver = "3"

[workspace.metadata]
default-run = "app"

[workspace.package]
authors = ["Kuma"]
description = "Seiran is a tool to generate PDF files from text files."
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Kumasan00/seiran"
version = "0.1.0"

[workspace.dependencies]
allsorts = "0.15.1"
harfbuzz_rs = "2.0.1"
pdf-writer = "0.14.0"
ttf-parser = "0.25.1"

[workspace.lints.clippy]
needless_return = "allow"

[profile.release]
debug = false
lto = true
opt-level = 3
