[workspace]
members = [
  "crates/cli",
  "crates/font",
  "crates/layout",
  "crates/parser",
  "crates/pdf_gen",
  "crates/read_config",
  "crates/read_references",
  "crates/read_style",
  "crates/seiran",
  "crates/types",
]
resolver = "3"

[workspace.metadata]
default-run = "app"

[workspace.package]
authors = ["Kuma"]
description = "Seiran is a tool to generate PDF files from text files."
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Kumasan00/seiran"
version = "0.1.0"

[workspace.dependencies]
allsorts = "0.16.1"
clap = { version = "4.5.60", features = ["derive"] }
figment = { version = "0.10.19", features = ["toml"] }
font-types = "0.11.0"
harfrust = "0.5.0"
icu = { version = "2.1.1", features = ["compiled_data"] }
lazy-regex = "3.6.0"
memchr = "2.8.0"
miette = { version = "7.6.0", features = ["fancy"] }
pdf-writer = "0.14.0"
phf = { version = "0.13.1", features = ["macros"] }
rayon = "1.11.0"
read-fonts = { version = "0.37.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "1.0.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["local-time"] }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
expect_used = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }
unwrap_used = { level = "warn", priority = 0 }

cast_possible_truncation = { level = "allow", priority = 1 }
needless_return = { level = "allow", priority = 1 }
too_many_lines = { level = "allow", priority = 1 }

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 3
strip = "symbols"
