absolute-paths-max-segments = 3
allow-mixed-uninlined-format-args = false
allow-panic-in-tests = true
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
upper-case-acronyms-aggressive = true
