[package]
name = "lowering"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
miette.workspace = true
parser.workspace = true
read_style.workspace = true
thiserror.workspace = true
types.workspace = true

[lints]
workspace = true
