[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "app"
version = "0.1.0"

[dependencies]
allsorts.workspace = true
cli = { path = "../cli" }
font = { path = "../font" }
harfbuzz_rs.workspace = true
pdf-writer.workspace = true
pdf_gen = { path = "../pdf_gen" }
read_file = { path = "../read_file" }
stypes = { path = "../stypes" }
text = { path = "../text" }
ttf-parser.workspace = true

[lints]
workspace = true
