[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "app"
version.workspace = true

[dependencies]
anyhow.workspace = true
cli = { path = "../cli" }
font = { path = "../font" }
pdf-writer.workspace = true
pdf_gen = { path = "../pdf_gen" }
read_config_file = { path = "../read_config_file" }
read_file = { path = "../read_file" }
stypes = { path = "../stypes" }
text = { path = "../text" }
ttf-parser.workspace = true

[lints]
workspace = true
