[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "pdf_gen"
version.workspace = true

[dependencies]
font = { path = "../font" }
parser = { path = "../parser" }
pdf-writer.workspace = true
read_config_file = { path = "../read_config_file" }
types = { path = "../types" }

[lints]
workspace = true
