[package]
name = "pdf_gen"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
font.workspace = true
krilla.workspace = true
krilla-svg.workspace = true
layout.workspace = true
miette.workspace = true
read_config.workspace = true
read-fonts.workspace = true
read_style.workspace = true
thiserror.workspace = true
types.workspace = true

[lints]
workspace = true
