[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "seiran"
version.workspace = true

[dependencies]
cli = { path = "../cli" }
font = { path = "../font" }
layout = { path = "../layout" }
miette.workspace = true
parser = { path = "../parser" }
pdf_gen = { path = "../pdf_gen" }
read_config = { path = "../read_config" }
read_references = { path = "../read_references" }
read_style = { path = "../read_style" }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
types = { path = "../types" }
subcommand = { path = "../subcommand" }

[lints]
workspace = true
