[package]
name = "frontend"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
memchr.workspace = true
miette.workspace = true
model.workspace = true
phf.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
