[package]
name = "seiran-compiler"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
ciborium.workspace = true
font-types.workspace = true
garde.workspace = true
harfrust.workspace = true
hayagriva.workspace = true
hypher.workspace = true
icu.workspace = true
lazy-regex.workspace = true
memchr.workspace = true
miette.workspace = true
phf.workspace = true
rayon.workspace = true
read-fonts.workspace = true
seiran-pdf.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
unic-langid.workspace = true

[dev-dependencies]
lopdf.workspace = true
proptest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
