[package]
name = "parser"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bumpalo.workspace = true
document.workspace = true
garde.workspace = true
miette.workspace = true
phf.workspace = true
read_style.workspace = true
serde.workspace = true
syntax.workspace = true
thiserror.workspace = true
tracing.workspace = true
types.workspace = true

[lints]
workspace = true
