[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "parser"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
font = { path = "../font" }
lazy-regex.workspace = true
memchr.workspace = true
memmap2.workspace = true
phf.workspace = true
read_config_file = { path = "../read_config_file" }
thiserror.workspace = true
types = { path = "../types" }

[lints]
workspace = true
