[package]
name = "hlist"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
hypher.workspace = true
icu.workspace = true
tracing.workspace = true
types.workspace = true

[lints]
workspace = true
