[package]
name = "citation"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
document.workspace = true
hayagriva.workspace = true
miette.workspace = true
read_references.workspace = true
read_style.workspace = true
thiserror.workspace = true
types.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
