//! 数式記号テーブル
//!
//! 単一の Unicode 文字と、アトム間のアキを決める数式クラスを保持する。

use phf::phf_map;

use crate::document::MathClass;

/// 記号コマンドが出力する単一文字とその数式クラス
#[derive(Clone, Copy, Debug)]
pub(in crate::frontend::evaluator) struct MathSymbol {
  /// 出力する Unicode 文字
  pub(crate) ch: char,
  /// 数式クラス
  pub(crate) class: MathClass,
}

impl MathSymbol {
  /// 記号エントリを生成する
  const fn new(ch: char, class: MathClass) -> Self { return Self { ch, class }; }
}

/// 記号コマンド名 → [`MathSymbol`] のパーフェクトハッシュマップ
static SYMBOLS: phf::Map<&'static str, MathSymbol> = phf_map! {
  // ギリシャ文字（大文字）
  "Alpha" => MathSymbol::new('\u{0391}', MathClass::Ord),
  "Beta" => MathSymbol::new('\u{0392}', MathClass::Ord),
  "Gamma" => MathSymbol::new('\u{0393}', MathClass::Ord),
  "Delta" => MathSymbol::new('\u{0394}', MathClass::Ord),
  "Epsilon" => MathSymbol::new('\u{0395}', MathClass::Ord),
  "Zeta" => MathSymbol::new('\u{0396}', MathClass::Ord),
  "Eta" => MathSymbol::new('\u{0397}', MathClass::Ord),
  "Theta" => MathSymbol::new('\u{0398}', MathClass::Ord),
  "Iota" => MathSymbol::new('\u{0399}', MathClass::Ord),
  "Kappa" => MathSymbol::new('\u{039A}', MathClass::Ord),
  "Lambda" => MathSymbol::new('\u{039B}', MathClass::Ord),
  "Mu" => MathSymbol::new('\u{039C}', MathClass::Ord),
  "Nu" => MathSymbol::new('\u{039D}', MathClass::Ord),
  "Xi" => MathSymbol::new('\u{039E}', MathClass::Ord),
  "Omicron" => MathSymbol::new('\u{039F}', MathClass::Ord),
  "Pi" => MathSymbol::new('\u{03A0}', MathClass::Ord),
  "Rho" => MathSymbol::new('\u{03A1}', MathClass::Ord),
  "Sigma" => MathSymbol::new('\u{03A3}', MathClass::Ord),
  "Tau" => MathSymbol::new('\u{03A4}', MathClass::Ord),
  "Upsilon" => MathSymbol::new('\u{03A5}', MathClass::Ord),
  "Phi" => MathSymbol::new('\u{03A6}', MathClass::Ord),
  "Chi" => MathSymbol::new('\u{03A7}', MathClass::Ord),
  "Psi" => MathSymbol::new('\u{03A8}', MathClass::Ord),
  "Omega" => MathSymbol::new('\u{03A9}', MathClass::Ord),

  // ギリシャ文字（小文字）
  "alpha" => MathSymbol::new('\u{03B1}', MathClass::Ord),
  "beta" => MathSymbol::new('\u{03B2}', MathClass::Ord),
  "gamma" => MathSymbol::new('\u{03B3}', MathClass::Ord),
  "delta" => MathSymbol::new('\u{03B4}', MathClass::Ord),
  "epsilon" => MathSymbol::new('\u{03F5}', MathClass::Ord),
  "varepsilon" => MathSymbol::new('\u{03B5}', MathClass::Ord),
  "zeta" => MathSymbol::new('\u{03B6}', MathClass::Ord),
  "eta" => MathSymbol::new('\u{03B7}', MathClass::Ord),
  "theta" => MathSymbol::new('\u{03B8}', MathClass::Ord),
  "vartheta" => MathSymbol::new('\u{03D1}', MathClass::Ord),
  "iota" => MathSymbol::new('\u{03B9}', MathClass::Ord),
  "kappa" => MathSymbol::new('\u{03BA}', MathClass::Ord),
  "varkappa" => MathSymbol::new('\u{03F0}', MathClass::Ord),
  "lambda" => MathSymbol::new('\u{03BB}', MathClass::Ord),
  "mu" => MathSymbol::new('\u{03BC}', MathClass::Ord),
  "nu" => MathSymbol::new('\u{03BD}', MathClass::Ord),
  "xi" => MathSymbol::new('\u{03BE}', MathClass::Ord),
  "omicron" => MathSymbol::new('\u{03BF}', MathClass::Ord),
  "pi" => MathSymbol::new('\u{03C0}', MathClass::Ord),
  "varpi" => MathSymbol::new('\u{03D6}', MathClass::Ord),
  "rho" => MathSymbol::new('\u{03C1}', MathClass::Ord),
  "varrho" => MathSymbol::new('\u{03F1}', MathClass::Ord),
  "sigma" => MathSymbol::new('\u{03C3}', MathClass::Ord),
  "varsigma" => MathSymbol::new('\u{03C2}', MathClass::Ord),
  "tau" => MathSymbol::new('\u{03C4}', MathClass::Ord),
  "upsilon" => MathSymbol::new('\u{03C5}', MathClass::Ord),
  "phi" => MathSymbol::new('\u{03D5}', MathClass::Ord),
  "varphi" => MathSymbol::new('\u{03C6}', MathClass::Ord),
  "chi" => MathSymbol::new('\u{03C7}', MathClass::Ord),
  "psi" => MathSymbol::new('\u{03C8}', MathClass::Ord),
  "omega" => MathSymbol::new('\u{03C9}', MathClass::Ord),

  // 名前付き記号・定数
  "forall" => MathSymbol::new('\u{2200}', MathClass::Ord),
  "complement" => MathSymbol::new('\u{2201}', MathClass::Ord),
  "partial" => MathSymbol::new('\u{2202}', MathClass::Ord),
  "exists" => MathSymbol::new('\u{2203}', MathClass::Ord),
  "notexists" => MathSymbol::new('\u{2204}', MathClass::Ord),
  "emptyset" => MathSymbol::new('\u{2205}', MathClass::Ord),
  "increment" => MathSymbol::new('\u{2206}', MathClass::Ord),
  "nabla" => MathSymbol::new('\u{2207}', MathClass::Ord),
  "qed" => MathSymbol::new('\u{220E}', MathClass::Ord),
  "surd" => MathSymbol::new('\u{221A}', MathClass::Ord),
  "infty" => MathSymbol::new('\u{221E}', MathClass::Ord),
  "rightangle" => MathSymbol::new('\u{221F}', MathClass::Ord),
  "angle" => MathSymbol::new('\u{2220}', MathClass::Ord),
  "measuredangle" => MathSymbol::new('\u{2221}', MathClass::Ord),
  "sphericalangle" => MathSymbol::new('\u{2222}', MathClass::Ord),
  "therefore" => MathSymbol::new('\u{2234}', MathClass::Ord),
  "because" => MathSymbol::new('\u{2235}', MathClass::Ord),
  "neg" => MathSymbol::new('\u{00AC}', MathClass::Ord),
  "hbar" => MathSymbol::new('\u{210F}', MathClass::Ord),
  "ell" => MathSymbol::new('\u{2113}', MathClass::Ord),
  "wp" => MathSymbol::new('\u{2118}', MathClass::Ord),
  "Re" => MathSymbol::new('\u{211C}', MathClass::Ord),
  "Im" => MathSymbol::new('\u{2111}', MathClass::Ord),
  "aleph" => MathSymbol::new('\u{2135}', MathClass::Ord),
  "beth" => MathSymbol::new('\u{2136}', MathClass::Ord),
  "gimel" => MathSymbol::new('\u{2137}', MathClass::Ord),
  "daleth" => MathSymbol::new('\u{2138}', MathClass::Ord),
  "mho" => MathSymbol::new('\u{2127}', MathClass::Ord),
  "Finv" => MathSymbol::new('\u{2132}', MathClass::Ord),
  "Game" => MathSymbol::new('\u{2141}', MathClass::Ord),
  "eth" => MathSymbol::new('\u{00F0}', MathClass::Ord),
  "prime" => MathSymbol::new('\u{2032}', MathClass::Ord),
  "backprime" => MathSymbol::new('\u{2035}', MathClass::Ord),
  "top" => MathSymbol::new('\u{22A4}', MathClass::Ord),
  "bot" => MathSymbol::new('\u{22A5}', MathClass::Ord),
  "triangle" => MathSymbol::new('\u{25B3}', MathClass::Ord),
  "blacktriangle" => MathSymbol::new('\u{25B4}', MathClass::Ord),
  "bigblacktriangleup" => MathSymbol::new('\u{25B2}', MathClass::Ord),
  "blacktriangledown" => MathSymbol::new('\u{25BE}', MathClass::Ord),
  "bigblacktriangledown" => MathSymbol::new('\u{25BC}', MathClass::Ord),
  "square" => MathSymbol::new('\u{25A1}', MathClass::Ord),
  "blacksquare" => MathSymbol::new('\u{25A0}', MathClass::Ord),
  "lozenge" => MathSymbol::new('\u{25CA}', MathClass::Ord),
  "blacklozenge" => MathSymbol::new('\u{29EB}', MathClass::Ord),
  "bigstar" => MathSymbol::new('\u{2605}', MathClass::Ord),
  "diagup" => MathSymbol::new('\u{27CB}', MathClass::Ord),
  "diagdown" => MathSymbol::new('\u{27CD}', MathClass::Ord),
  "sharp" => MathSymbol::new('\u{266F}', MathClass::Ord),
  "flat" => MathSymbol::new('\u{266D}', MathClass::Ord),
  "natural" => MathSymbol::new('\u{266E}', MathClass::Ord),
  "clubsuit" => MathSymbol::new('\u{2663}', MathClass::Ord),
  "diamondsuit" => MathSymbol::new('\u{2662}', MathClass::Ord),
  "heartsuit" => MathSymbol::new('\u{2661}', MathClass::Ord),
  "spadesuit" => MathSymbol::new('\u{2660}', MathClass::Ord),
  "checkmark" => MathSymbol::new('\u{2713}', MathClass::Ord),
  "maltese" => MathSymbol::new('\u{2720}', MathClass::Ord),
  "circledR" => MathSymbol::new('\u{00AE}', MathClass::Ord),
  "circledS" => MathSymbol::new('\u{24C8}', MathClass::Ord),
  "ldots" => MathSymbol::new('\u{2026}', MathClass::Ord),
  "cdots" => MathSymbol::new('\u{22EF}', MathClass::Ord),
  "vdots" => MathSymbol::new('\u{22EE}', MathClass::Ord),
  "ddots" => MathSymbol::new('\u{22F1}', MathClass::Ord),
  "colon" => MathSymbol::new('\u{003A}', MathClass::Punct),
  "backslash" => MathSymbol::new('\u{005C}', MathClass::Ord),
  "sterling" => MathSymbol::new('\u{00A3}', MathClass::Ord),
  "yen" => MathSymbol::new('\u{00A5}', MathClass::Ord),
  "sectionsign" => MathSymbol::new('\u{00A7}', MathClass::Ord),
  "paragraphsign" => MathSymbol::new('\u{00B6}', MathClass::Ord),
  "Zbar" => MathSymbol::new('\u{01B5}', MathClass::Ord),
  "backepsilon" => MathSymbol::new('\u{03F6}', MathClass::Ord),
  "horizontalbar" => MathSymbol::new('\u{2015}', MathClass::Ord),
  "doublelowline" => MathSymbol::new('\u{2017}', MathClass::Ord),
  "twodotleader" => MathSymbol::new('\u{2025}', MathClass::Ord),
  "doubleprime" => MathSymbol::new('\u{2033}', MathClass::Ord),
  "tripleprime" => MathSymbol::new('\u{2034}', MathClass::Ord),
  "backdoubleprime" => MathSymbol::new('\u{2036}', MathClass::Ord),
  "backtripleprime" => MathSymbol::new('\u{2037}', MathClass::Ord),
  "caret" => MathSymbol::new('\u{2038}', MathClass::Ord),
  "doubleexclam" => MathSymbol::new('\u{203C}', MathClass::Ord),
  "hyphenbullet" => MathSymbol::new('\u{2043}', MathClass::Ord),
  "doublequestion" => MathSymbol::new('\u{2047}', MathClass::Ord),
  "quadrupleprime" => MathSymbol::new('\u{2057}', MathClass::Ord),
  "euro" => MathSymbol::new('\u{20AC}', MathClass::Ord),
  "eulerconstant" => MathSymbol::new('\u{2107}', MathClass::Ord),
  "doublestruckpi" => MathSymbol::new('\u{213C}', MathClass::Ord),
  "turnedsansL" => MathSymbol::new('\u{2142}', MathClass::Ord),
  "reversedsansL" => MathSymbol::new('\u{2143}', MathClass::Ord),
  "turnedsansY" => MathSymbol::new('\u{2144}', MathClass::Ord),
  "differentialD" => MathSymbol::new('\u{2145}', MathClass::Ord),
  "differentiald" => MathSymbol::new('\u{2146}', MathClass::Ord),
  "exponentiale" => MathSymbol::new('\u{2147}', MathClass::Ord),
  "imaginaryi" => MathSymbol::new('\u{2148}', MathClass::Ord),
  "imaginaryj" => MathSymbol::new('\u{2149}', MathClass::Ord),
  "propertyline" => MathSymbol::new('\u{214A}', MathClass::Ord),
  "updownarrowbar" => MathSymbol::new('\u{21A8}', MathClass::Ord),
  "linefeed" => MathSymbol::new('\u{21B4}', MathClass::Ord),
  "carriagereturn" => MathSymbol::new('\u{21B5}', MathClass::Ord),
  "barovernorthwestarrow" => MathSymbol::new('\u{21B8}', MathClass::Ord),
  "barleftarrowrightarrowbar" => MathSymbol::new('\u{21B9}', MathClass::Ord),
  "uparrowdoublestroke" => MathSymbol::new('\u{21DE}', MathClass::Ord),
  "downarrowdoublestroke" => MathSymbol::new('\u{21DF}', MathClass::Ord),
  "leftdasharrow" => MathSymbol::new('\u{21E0}', MathClass::Ord),
  "updasharrow" => MathSymbol::new('\u{21E1}', MathClass::Ord),
  "rightdasharrow" => MathSymbol::new('\u{21E2}', MathClass::Ord),
  "downdasharrow" => MathSymbol::new('\u{21E3}', MathClass::Ord),
  "leftwhitearrow" => MathSymbol::new('\u{21E6}', MathClass::Ord),
  "upwhitearrow" => MathSymbol::new('\u{21E7}', MathClass::Ord),
  "rightwhitearrow" => MathSymbol::new('\u{21E8}', MathClass::Ord),
  "downwhitearrow" => MathSymbol::new('\u{21E9}', MathClass::Ord),
  "whitearrowupfrombar" => MathSymbol::new('\u{21EA}', MathClass::Ord),
  "cuberoot" => MathSymbol::new('\u{221B}', MathClass::Ord),
  "fourthroot" => MathSymbol::new('\u{221C}', MathClass::Ord),
  "sinewave" => MathSymbol::new('\u{223F}', MathClass::Ord),
  "hermitianmatrix" => MathSymbol::new('\u{22B9}', MathClass::Ord),
  "measuredrightangle" => MathSymbol::new('\u{22BE}', MathClass::Ord),
  "righttriangle" => MathSymbol::new('\u{22BF}', MathClass::Ord),
  "adots" => MathSymbol::new('\u{22F0}', MathClass::Ord),
  "diameter" => MathSymbol::new('\u{2300}', MathClass::Ord),
  "house" => MathSymbol::new('\u{2302}', MathClass::Ord),
  "reversednot" => MathSymbol::new('\u{2310}', MathClass::Ord),
  "squarelozenge" => MathSymbol::new('\u{2311}', MathClass::Ord),
  "profileline" => MathSymbol::new('\u{2312}', MathClass::Ord),
  "profilesurface" => MathSymbol::new('\u{2313}', MathClass::Ord),
  "viewdata" => MathSymbol::new('\u{2317}', MathClass::Ord),
  "turnednot" => MathSymbol::new('\u{2319}', MathClass::Ord),
  "hexagonbonds" => MathSymbol::new('\u{232C}', MathClass::Ord),
  "conictaper" => MathSymbol::new('\u{2332}', MathClass::Ord),
  "topbot" => MathSymbol::new('\u{2336}', MathClass::Ord),
  "backslashbar" => MathSymbol::new('\u{2340}', MathClass::Ord),
  "boxedcaret" => MathSymbol::new('\u{2353}', MathClass::Ord),
  "boxedquestion" => MathSymbol::new('\u{2370}', MathClass::Ord),
  "rangledownzigzagarrow" => MathSymbol::new('\u{237C}', MathClass::Ord),
  "hexagon" => MathSymbol::new('\u{2394}', MathClass::Ord),
  "stackedbrackets" => MathSymbol::new('\u{23B6}', MathClass::Ord),
  "leftboxline" => MathSymbol::new('\u{23B8}', MathClass::Ord),
  "rightboxline" => MathSymbol::new('\u{23B9}', MathClass::Ord),
  "returnsymbol" => MathSymbol::new('\u{23CE}', MathClass::Ord),
  "toptortoise" => MathSymbol::new('\u{23E0}', MathClass::Ord),
  "bottomtortoise" => MathSymbol::new('\u{23E1}', MathClass::Ord),
  "trapezium" => MathSymbol::new('\u{23E2}', MathClass::Ord),
  "benzenering" => MathSymbol::new('\u{23E3}', MathClass::Ord),
  "straightness" => MathSymbol::new('\u{23E4}', MathClass::Ord),
  "flatness" => MathSymbol::new('\u{23E5}', MathClass::Ord),
  "accurrent" => MathSymbol::new('\u{23E6}', MathClass::Ord),
  "electricalintersection" => MathSymbol::new('\u{23E7}', MathClass::Ord),
  "blanksymbol" => MathSymbol::new('\u{2422}', MathClass::Ord),
  "visiblespace" => MathSymbol::new('\u{2423}', MathClass::Ord),
  "dashedvert" => MathSymbol::new('\u{2506}', MathClass::Ord),
  "upperhalfblock" => MathSymbol::new('\u{2580}', MathClass::Ord),
  "lowerhalfblock" => MathSymbol::new('\u{2584}', MathClass::Ord),
  "fullblock" => MathSymbol::new('\u{2588}', MathClass::Ord),
  "lefthalfblock" => MathSymbol::new('\u{258C}', MathClass::Ord),
  "righthalfblock" => MathSymbol::new('\u{2590}', MathClass::Ord),
  "lightshade" => MathSymbol::new('\u{2591}', MathClass::Ord),
  "mediumshade" => MathSymbol::new('\u{2592}', MathClass::Ord),
  "darkshade" => MathSymbol::new('\u{2593}', MathClass::Ord),
  "roundedsquare" => MathSymbol::new('\u{25A2}', MathClass::Ord),
  "blackinwhitesquare" => MathSymbol::new('\u{25A3}', MathClass::Ord),
  "squarehfill" => MathSymbol::new('\u{25A4}', MathClass::Ord),
  "squarevfill" => MathSymbol::new('\u{25A5}', MathClass::Ord),
  "squarehvfill" => MathSymbol::new('\u{25A6}', MathClass::Ord),
  "squarenwsefill" => MathSymbol::new('\u{25A7}', MathClass::Ord),
  "squareneswfill" => MathSymbol::new('\u{25A8}', MathClass::Ord),
  "squarecrossfill" => MathSymbol::new('\u{25A9}', MathClass::Ord),
  "smallblacksquare" => MathSymbol::new('\u{25AA}', MathClass::Ord),
  "smallsquare" => MathSymbol::new('\u{25AB}', MathClass::Ord),
  "hrectangleblack" => MathSymbol::new('\u{25AC}', MathClass::Ord),
  "hrectangle" => MathSymbol::new('\u{25AD}', MathClass::Ord),
  "vrectangleblack" => MathSymbol::new('\u{25AE}', MathClass::Ord),
  "vrectangle" => MathSymbol::new('\u{25AF}', MathClass::Ord),
  "parallelogramblack" => MathSymbol::new('\u{25B0}', MathClass::Ord),
  "parallelogram" => MathSymbol::new('\u{25B1}', MathClass::Ord),
  "blacktriangleright" => MathSymbol::new('\u{25B6}', MathClass::Ord),
  "smallblacktriangleright" => MathSymbol::new('\u{25B8}', MathClass::Ord),
  "smalltriangleright" => MathSymbol::new('\u{25B9}', MathClass::Ord),
  "blackpointerright" => MathSymbol::new('\u{25BA}', MathClass::Ord),
  "whitepointerright" => MathSymbol::new('\u{25BB}', MathClass::Ord),
  "triangledown" => MathSymbol::new('\u{25BF}', MathClass::Ord),
  "blacktriangleleft" => MathSymbol::new('\u{25C0}', MathClass::Ord),
  "smallblacktriangleleft" => MathSymbol::new('\u{25C2}', MathClass::Ord),
  "smalltriangleleft" => MathSymbol::new('\u{25C3}', MathClass::Ord),
  "blackpointerleft" => MathSymbol::new('\u{25C4}', MathClass::Ord),
  "whitepointerleft" => MathSymbol::new('\u{25C5}', MathClass::Ord),
  "blackdiamond" => MathSymbol::new('\u{25C6}', MathClass::Ord),
  "whitediamond" => MathSymbol::new('\u{25C7}', MathClass::Ord),
  "blackinwhitediamond" => MathSymbol::new('\u{25C8}', MathClass::Ord),
  "fisheye" => MathSymbol::new('\u{25C9}', MathClass::Ord),
  "dottedcircle" => MathSymbol::new('\u{25CC}', MathClass::Ord),
  "circlevertfill" => MathSymbol::new('\u{25CD}', MathClass::Ord),
  "bullseye" => MathSymbol::new('\u{25CE}', MathClass::Ord),
  "blackcircle" => MathSymbol::new('\u{25CF}', MathClass::Ord),
  "circlelefthalfblack" => MathSymbol::new('\u{25D0}', MathClass::Ord),
  "circlerighthalfblack" => MathSymbol::new('\u{25D1}', MathClass::Ord),
  "circlebottomhalfblack" => MathSymbol::new('\u{25D2}', MathClass::Ord),
  "circletophalfblack" => MathSymbol::new('\u{25D3}', MathClass::Ord),
  "circleurquadblack" => MathSymbol::new('\u{25D4}', MathClass::Ord),
  "blackcircleulquadwhite" => MathSymbol::new('\u{25D5}', MathClass::Ord),
  "blacklefthalfcircle" => MathSymbol::new('\u{25D6}', MathClass::Ord),
  "blackrighthalfcircle" => MathSymbol::new('\u{25D7}', MathClass::Ord),
  "inversebullet" => MathSymbol::new('\u{25D8}', MathClass::Ord),
  "inversewhitecircle" => MathSymbol::new('\u{25D9}', MathClass::Ord),
  "invwhiteupperhalfcircle" => MathSymbol::new('\u{25DA}', MathClass::Ord),
  "invwhitelowerhalfcircle" => MathSymbol::new('\u{25DB}', MathClass::Ord),
  "ularc" => MathSymbol::new('\u{25DC}', MathClass::Ord),
  "urarc" => MathSymbol::new('\u{25DD}', MathClass::Ord),
  "lrarc" => MathSymbol::new('\u{25DE}', MathClass::Ord),
  "llarc" => MathSymbol::new('\u{25DF}', MathClass::Ord),
  "topsemicircle" => MathSymbol::new('\u{25E0}', MathClass::Ord),
  "botsemicircle" => MathSymbol::new('\u{25E1}', MathClass::Ord),
  "lrblacktriangle" => MathSymbol::new('\u{25E2}', MathClass::Ord),
  "llblacktriangle" => MathSymbol::new('\u{25E3}', MathClass::Ord),
  "ulblacktriangle" => MathSymbol::new('\u{25E4}', MathClass::Ord),
  "urblacktriangle" => MathSymbol::new('\u{25E5}', MathClass::Ord),
  "smallcircle" => MathSymbol::new('\u{25E6}', MathClass::Ord),
  "squareleftblack" => MathSymbol::new('\u{25E7}', MathClass::Ord),
  "squarerightblack" => MathSymbol::new('\u{25E8}', MathClass::Ord),
  "squareulblack" => MathSymbol::new('\u{25E9}', MathClass::Ord),
  "squarelrblack" => MathSymbol::new('\u{25EA}', MathClass::Ord),
  "trianglecdot" => MathSymbol::new('\u{25EC}', MathClass::Ord),
  "triangleleftblack" => MathSymbol::new('\u{25ED}', MathClass::Ord),
  "trianglerightblack" => MathSymbol::new('\u{25EE}', MathClass::Ord),
  "bigcirc" => MathSymbol::new('\u{25EF}', MathClass::Ord),
  "squareulquad" => MathSymbol::new('\u{25F0}', MathClass::Ord),
  "squarellquad" => MathSymbol::new('\u{25F1}', MathClass::Ord),
  "squarelrquad" => MathSymbol::new('\u{25F2}', MathClass::Ord),
  "squareurquad" => MathSymbol::new('\u{25F3}', MathClass::Ord),
  "circleulquad" => MathSymbol::new('\u{25F4}', MathClass::Ord),
  "circlellquad" => MathSymbol::new('\u{25F5}', MathClass::Ord),
  "circlelrquad" => MathSymbol::new('\u{25F6}', MathClass::Ord),
  "circleurquad" => MathSymbol::new('\u{25F7}', MathClass::Ord),
  "ultriangle" => MathSymbol::new('\u{25F8}', MathClass::Ord),
  "urtriangle" => MathSymbol::new('\u{25F9}', MathClass::Ord),
  "lltriangle" => MathSymbol::new('\u{25FA}', MathClass::Ord),
  "mediumsquare" => MathSymbol::new('\u{25FB}', MathClass::Ord),
  "mediumblacksquare" => MathSymbol::new('\u{25FC}', MathClass::Ord),
  "mediumsmallsquare" => MathSymbol::new('\u{25FD}', MathClass::Ord),
  "mediumsmallblacksquare" => MathSymbol::new('\u{25FE}', MathClass::Ord),
  "lrtriangle" => MathSymbol::new('\u{25FF}', MathClass::Ord),
  "bigwhitestar" => MathSymbol::new('\u{2606}', MathClass::Ord),
  "astrosun" => MathSymbol::new('\u{2609}', MathClass::Ord),
  "danger" => MathSymbol::new('\u{2621}', MathClass::Ord),
  "blacksmiley" => MathSymbol::new('\u{263B}', MathClass::Ord),
  "sun" => MathSymbol::new('\u{263C}', MathClass::Ord),
  "rightmoon" => MathSymbol::new('\u{263D}', MathClass::Ord),
  "leftmoon" => MathSymbol::new('\u{263E}', MathClass::Ord),
  "female" => MathSymbol::new('\u{2640}', MathClass::Ord),
  "male" => MathSymbol::new('\u{2642}', MathClass::Ord),
  "whitespadesuit" => MathSymbol::new('\u{2664}', MathClass::Ord),
  "blackheartsuit" => MathSymbol::new('\u{2665}', MathClass::Ord),
  "blackdiamondsuit" => MathSymbol::new('\u{2666}', MathClass::Ord),
  "whiteclubsuit" => MathSymbol::new('\u{2667}', MathClass::Ord),
  "quarternote" => MathSymbol::new('\u{2669}', MathClass::Ord),
  "eighthnote" => MathSymbol::new('\u{266A}', MathClass::Ord),
  "twonotes" => MathSymbol::new('\u{266B}', MathClass::Ord),
  "permanentpaper" => MathSymbol::new('\u{267E}', MathClass::Ord),
  "diceone" => MathSymbol::new('\u{2680}', MathClass::Ord),
  "dicetwo" => MathSymbol::new('\u{2681}', MathClass::Ord),
  "dicethree" => MathSymbol::new('\u{2682}', MathClass::Ord),
  "dicefour" => MathSymbol::new('\u{2683}', MathClass::Ord),
  "dicefive" => MathSymbol::new('\u{2684}', MathClass::Ord),
  "dicesix" => MathSymbol::new('\u{2685}', MathClass::Ord),
  "circledrightdot" => MathSymbol::new('\u{2686}', MathClass::Ord),
  "circledtwodots" => MathSymbol::new('\u{2687}', MathClass::Ord),
  "blackcircledrightdot" => MathSymbol::new('\u{2688}', MathClass::Ord),
  "blackcircledtwodots" => MathSymbol::new('\u{2689}', MathClass::Ord),
  "hermaphrodite" => MathSymbol::new('\u{26A5}', MathClass::Ord),
  "mediumcircle" => MathSymbol::new('\u{26AA}', MathClass::Ord),
  "mediumblackcircle" => MathSymbol::new('\u{26AB}', MathClass::Ord),
  "mediumsmallcircle" => MathSymbol::new('\u{26AC}', MathClass::Ord),
  "neuter" => MathSymbol::new('\u{26B2}', MathClass::Ord),
  "circledstar" => MathSymbol::new('\u{272A}', MathClass::Ord),
  "sixpointstar" => MathSymbol::new('\u{2736}', MathClass::Ord),
  "heavyasterisk" => MathSymbol::new('\u{273D}', MathClass::Ord),
  "draftingarrow" => MathSymbol::new('\u{279B}', MathClass::Ord),
  "threedangle" => MathSymbol::new('\u{27C0}', MathClass::Ord),
  "whiteinwhitetriangle" => MathSymbol::new('\u{27C1}', MathClass::Ord),
  "subsetcirc" => MathSymbol::new('\u{27C3}', MathClass::Ord),
  "supsetcirc" => MathSymbol::new('\u{27C4}', MathClass::Ord),
  "longdivision" => MathSymbol::new('\u{27CC}', MathClass::Ord),
  "diamondcdot" => MathSymbol::new('\u{27D0}', MathClass::Ord),
  "rdiagovfdiag" => MathSymbol::new('\u{292B}', MathClass::Ord),
  "fdiagovrdiag" => MathSymbol::new('\u{292C}', MathClass::Ord),
  "seovnearrow" => MathSymbol::new('\u{292D}', MathClass::Ord),
  "neovsearrow" => MathSymbol::new('\u{292E}', MathClass::Ord),
  "fdiagovnearrow" => MathSymbol::new('\u{292F}', MathClass::Ord),
  "rdiagovsearrow" => MathSymbol::new('\u{2930}', MathClass::Ord),
  "neovnwarrow" => MathSymbol::new('\u{2931}', MathClass::Ord),
  "nwovnearrow" => MathSymbol::new('\u{2932}', MathClass::Ord),
  "uprightcurvearrow" => MathSymbol::new('\u{2934}', MathClass::Ord),
  "downrightcurvedarrow" => MathSymbol::new('\u{2935}', MathClass::Ord),
  "Vvert" => MathSymbol::new('\u{2980}', MathClass::Ord),
  "mediumsmallblackcircle" => MathSymbol::new('\u{2981}', MathClass::Ord),
  "fourvdots" => MathSymbol::new('\u{2999}', MathClass::Ord),
  "vzigzag" => MathSymbol::new('\u{299A}', MathClass::Ord),
  "measuredangleleft" => MathSymbol::new('\u{299B}', MathClass::Ord),
  "rightanglesquare" => MathSymbol::new('\u{299C}', MathClass::Ord),
  "rightangledot" => MathSymbol::new('\u{299D}', MathClass::Ord),
  "sangle" => MathSymbol::new('\u{299E}', MathClass::Ord),
  "acuteangle" => MathSymbol::new('\u{299F}', MathClass::Ord),
  "sphericalangleleft" => MathSymbol::new('\u{29A0}', MathClass::Ord),
  "sphericalangleup" => MathSymbol::new('\u{29A1}', MathClass::Ord),
  "turnedangle" => MathSymbol::new('\u{29A2}', MathClass::Ord),
  "reversedangle" => MathSymbol::new('\u{29A3}', MathClass::Ord),
  "angleubar" => MathSymbol::new('\u{29A4}', MathClass::Ord),
  "reversedangleubar" => MathSymbol::new('\u{29A5}', MathClass::Ord),
  "wideangledown" => MathSymbol::new('\u{29A6}', MathClass::Ord),
  "wideangleup" => MathSymbol::new('\u{29A7}', MathClass::Ord),
  "measanglerutone" => MathSymbol::new('\u{29A8}', MathClass::Ord),
  "measanglelutonw" => MathSymbol::new('\u{29A9}', MathClass::Ord),
  "measanglerdtose" => MathSymbol::new('\u{29AA}', MathClass::Ord),
  "measangleldtosw" => MathSymbol::new('\u{29AB}', MathClass::Ord),
  "measangleurtone" => MathSymbol::new('\u{29AC}', MathClass::Ord),
  "measangleultonw" => MathSymbol::new('\u{29AD}', MathClass::Ord),
  "measangledrtose" => MathSymbol::new('\u{29AE}', MathClass::Ord),
  "measangledltosw" => MathSymbol::new('\u{29AF}', MathClass::Ord),
  "reversedemptyset" => MathSymbol::new('\u{29B0}', MathClass::Ord),
  "emptysetobar" => MathSymbol::new('\u{29B1}', MathClass::Ord),
  "emptysetocirc" => MathSymbol::new('\u{29B2}', MathClass::Ord),
  "emptysetrightarrow" => MathSymbol::new('\u{29B3}', MathClass::Ord),
  "emptysetleftarrow" => MathSymbol::new('\u{29B4}', MathClass::Ord),
  "obot" => MathSymbol::new('\u{29BA}', MathClass::Ord),
  "olcross" => MathSymbol::new('\u{29BB}', MathClass::Ord),
  "odotslashdot" => MathSymbol::new('\u{29BC}', MathClass::Ord),
  "uparrowoncircle" => MathSymbol::new('\u{29BD}', MathClass::Ord),
  "circledwhitebullet" => MathSymbol::new('\u{29BE}', MathClass::Ord),
  "circledbullet" => MathSymbol::new('\u{29BF}', MathClass::Ord),
  "cirscir" => MathSymbol::new('\u{29C2}', MathClass::Ord),
  "cirE" => MathSymbol::new('\u{29C3}', MathClass::Ord),
  "boxonbox" => MathSymbol::new('\u{29C9}', MathClass::Ord),
  "triangleodot" => MathSymbol::new('\u{29CA}', MathClass::Ord),
  "triangleubar" => MathSymbol::new('\u{29CB}', MathClass::Ord),
  "striangle" => MathSymbol::new('\u{29CC}', MathClass::Ord),
  "incompleteinfty" => MathSymbol::new('\u{29DC}', MathClass::Ord),
  "tieinfty" => MathSymbol::new('\u{29DD}', MathClass::Ord),
  "nvinfty" => MathSymbol::new('\u{29DE}', MathClass::Ord),
  "contouredsquare" => MathSymbol::new('\u{29E0}', MathClass::Ord),
  "thermodynamic" => MathSymbol::new('\u{29E7}', MathClass::Ord),
  "downtriangleleftblack" => MathSymbol::new('\u{29E8}', MathClass::Ord),
  "downtrianglerightblack" => MathSymbol::new('\u{29E9}', MathClass::Ord),
  "blackdiamonddownarrow" => MathSymbol::new('\u{29EA}', MathClass::Ord),
  "circledownarrow" => MathSymbol::new('\u{29EC}', MathClass::Ord),
  "blackcircledownarrow" => MathSymbol::new('\u{29ED}', MathClass::Ord),
  "errbarsquare" => MathSymbol::new('\u{29EE}', MathClass::Ord),
  "errbarblacksquare" => MathSymbol::new('\u{29EF}', MathClass::Ord),
  "errbardiamond" => MathSymbol::new('\u{29F0}', MathClass::Ord),
  "errbarblackdiamond" => MathSymbol::new('\u{29F1}', MathClass::Ord),
  "errbarcircle" => MathSymbol::new('\u{29F2}', MathClass::Ord),
  "errbarblackcircle" => MathSymbol::new('\u{29F3}', MathClass::Ord),
  "perps" => MathSymbol::new('\u{2AE1}', MathClass::Ord),
  "topcir" => MathSymbol::new('\u{2AF1}', MathClass::Ord),
  "squaretopblack" => MathSymbol::new('\u{2B12}', MathClass::Ord),
  "squarebotblack" => MathSymbol::new('\u{2B13}', MathClass::Ord),
  "squareurblack" => MathSymbol::new('\u{2B14}', MathClass::Ord),
  "squarellblack" => MathSymbol::new('\u{2B15}', MathClass::Ord),
  "diamondleftblack" => MathSymbol::new('\u{2B16}', MathClass::Ord),
  "diamondrightblack" => MathSymbol::new('\u{2B17}', MathClass::Ord),
  "diamondtopblack" => MathSymbol::new('\u{2B18}', MathClass::Ord),
  "diamondbotblack" => MathSymbol::new('\u{2B19}', MathClass::Ord),
  "dottedsquare" => MathSymbol::new('\u{2B1A}', MathClass::Ord),
  "largeblacksquare" => MathSymbol::new('\u{2B1B}', MathClass::Ord),
  "largesquare" => MathSymbol::new('\u{2B1C}', MathClass::Ord),
  "tinyblacksquare" => MathSymbol::new('\u{2B1D}', MathClass::Ord),
  "tinysquare" => MathSymbol::new('\u{2B1E}', MathClass::Ord),
  "pentagonblack" => MathSymbol::new('\u{2B1F}', MathClass::Ord),
  "pentagon" => MathSymbol::new('\u{2B20}', MathClass::Ord),
  "varhexagon" => MathSymbol::new('\u{2B21}', MathClass::Ord),
  "varhexagonblack" => MathSymbol::new('\u{2B22}', MathClass::Ord),
  "hexagonblack" => MathSymbol::new('\u{2B23}', MathClass::Ord),
  "largeblackcircle" => MathSymbol::new('\u{2B24}', MathClass::Ord),
  "mediumblackdiamond" => MathSymbol::new('\u{2B25}', MathClass::Ord),
  "mediumdiamond" => MathSymbol::new('\u{2B26}', MathClass::Ord),
  "mediumblacklozenge" => MathSymbol::new('\u{2B27}', MathClass::Ord),
  "mediumlozenge" => MathSymbol::new('\u{2B28}', MathClass::Ord),
  "smallblackdiamond" => MathSymbol::new('\u{2B29}', MathClass::Ord),
  "smallblacklozenge" => MathSymbol::new('\u{2B2A}', MathClass::Ord),
  "smalllozenge" => MathSymbol::new('\u{2B2B}', MathClass::Ord),
  "blackhorizontalellipse" => MathSymbol::new('\u{2B2C}', MathClass::Ord),
  "horizontalellipse" => MathSymbol::new('\u{2B2D}', MathClass::Ord),
  "blackverticalellipse" => MathSymbol::new('\u{2B2E}', MathClass::Ord),
  "verticalellipse" => MathSymbol::new('\u{2B2F}', MathClass::Ord),
  "mediumwhitestar" => MathSymbol::new('\u{2B50}', MathClass::Ord),
  "mediumblackstar" => MathSymbol::new('\u{2B51}', MathClass::Ord),
  "smallwhitestar" => MathSymbol::new('\u{2B52}', MathClass::Ord),
  "rightpentagonblack" => MathSymbol::new('\u{2B53}', MathClass::Ord),
  "rightpentagon" => MathSymbol::new('\u{2B54}', MathClass::Ord),
  "postalmark" => MathSymbol::new('\u{3012}', MathClass::Ord),
  "hzigzag" => MathSymbol::new('\u{3030}', MathClass::Ord),

  // 大型演算子
  "prod" => MathSymbol::new('\u{220F}', MathClass::Op),
  "coprod" => MathSymbol::new('\u{2210}', MathClass::Op),
  "sum" => MathSymbol::new('\u{2211}', MathClass::Op),
  "int" => MathSymbol::new('\u{222B}', MathClass::Op),
  "iint" => MathSymbol::new('\u{222C}', MathClass::Op),
  "iiint" => MathSymbol::new('\u{222D}', MathClass::Op),
  "oint" => MathSymbol::new('\u{222E}', MathClass::Op),
  "oiint" => MathSymbol::new('\u{222F}', MathClass::Op),
  "oiiint" => MathSymbol::new('\u{2230}', MathClass::Op),
  "bigcap" => MathSymbol::new('\u{22C2}', MathClass::Op),
  "bigcup" => MathSymbol::new('\u{22C3}', MathClass::Op),
  "bigsqcup" => MathSymbol::new('\u{2A06}', MathClass::Op),
  "bigvee" => MathSymbol::new('\u{22C1}', MathClass::Op),
  "bigwedge" => MathSymbol::new('\u{22C0}', MathClass::Op),
  "bigodot" => MathSymbol::new('\u{2A00}', MathClass::Op),
  "bigoplus" => MathSymbol::new('\u{2A01}', MathClass::Op),
  "bigotimes" => MathSymbol::new('\u{2A02}', MathClass::Op),
  "biguplus" => MathSymbol::new('\u{2A04}', MathClass::Op),
  "doublestrucksum" => MathSymbol::new('\u{2140}', MathClass::Op),
  "intclockwise" => MathSymbol::new('\u{2231}', MathClass::Op),
  "ointclockwise" => MathSymbol::new('\u{2232}', MathClass::Op),
  "ointcounterclockwise" => MathSymbol::new('\u{2233}', MathClass::Op),
  "leftouterjoin" => MathSymbol::new('\u{27D5}', MathClass::Op),
  "rightouterjoin" => MathSymbol::new('\u{27D6}', MathClass::Op),
  "fullouterjoin" => MathSymbol::new('\u{27D7}', MathClass::Op),
  "bigbot" => MathSymbol::new('\u{27D8}', MathClass::Op),
  "bigtop" => MathSymbol::new('\u{27D9}', MathClass::Op),
  "bigslash" => MathSymbol::new('\u{29F8}', MathClass::Op),
  "bigbackslash" => MathSymbol::new('\u{29F9}', MathClass::Op),
  "bigcupdot" => MathSymbol::new('\u{2A03}', MathClass::Op),
  "bigsqcap" => MathSymbol::new('\u{2A05}', MathClass::Op),
  "conjquant" => MathSymbol::new('\u{2A07}', MathClass::Op),
  "disjquant" => MathSymbol::new('\u{2A08}', MathClass::Op),
  "bigtimes" => MathSymbol::new('\u{2A09}', MathClass::Op),
  "modtwosum" => MathSymbol::new('\u{2A0A}', MathClass::Op),
  "sumint" => MathSymbol::new('\u{2A0B}', MathClass::Op),
  "iiiint" => MathSymbol::new('\u{2A0C}', MathClass::Op),
  "intbar" => MathSymbol::new('\u{2A0D}', MathClass::Op),
  "intBar" => MathSymbol::new('\u{2A0E}', MathClass::Op),
  "fint" => MathSymbol::new('\u{2A0F}', MathClass::Op),
  "circulationint" => MathSymbol::new('\u{2A10}', MathClass::Op),
  "awint" => MathSymbol::new('\u{2A11}', MathClass::Op),
  "rppolint" => MathSymbol::new('\u{2A12}', MathClass::Op),
  "scpolint" => MathSymbol::new('\u{2A13}', MathClass::Op),
  "npolint" => MathSymbol::new('\u{2A14}', MathClass::Op),
  "pointint" => MathSymbol::new('\u{2A15}', MathClass::Op),
  "sqint" => MathSymbol::new('\u{2A16}', MathClass::Op),
  "intlefthookarrow" => MathSymbol::new('\u{2A17}', MathClass::Op),
  "inttimes" => MathSymbol::new('\u{2A18}', MathClass::Op),
  "intcap" => MathSymbol::new('\u{2A19}', MathClass::Op),
  "intcup" => MathSymbol::new('\u{2A1A}', MathClass::Op),
  "upint" => MathSymbol::new('\u{2A1B}', MathClass::Op),
  "lowint" => MathSymbol::new('\u{2A1C}', MathClass::Op),
  "Join" => MathSymbol::new('\u{2A1D}', MathClass::Op),
  "bigtriangleleft" => MathSymbol::new('\u{2A1E}', MathClass::Op),
  "schemacompose" => MathSymbol::new('\u{2A1F}', MathClass::Op),
  "schemapipe" => MathSymbol::new('\u{2A20}', MathClass::Op),
  "schemaproject" => MathSymbol::new('\u{2A21}', MathClass::Op),
  "biginterleave" => MathSymbol::new('\u{2AFC}', MathClass::Op),
  "bigwhitevert" => MathSymbol::new('\u{2AFF}', MathClass::Op),
  "arabicmaj" => MathSymbol::new('\u{1EEF0}', MathClass::Op),
  "arabichad" => MathSymbol::new('\u{1EEF1}', MathClass::Op),

  // 二項演算子
  "minus" => MathSymbol::new('\u{2212}', MathClass::Bin),
  "mp" => MathSymbol::new('\u{2213}', MathClass::Bin),
  "pm" => MathSymbol::new('\u{00B1}', MathClass::Bin),
  "dotplus" => MathSymbol::new('\u{2214}', MathClass::Bin),
  "slash" => MathSymbol::new('\u{2215}', MathClass::Bin),
  "times" => MathSymbol::new('\u{00D7}', MathClass::Bin),
  "div" => MathSymbol::new('\u{00F7}', MathClass::Bin),
  "cdot" => MathSymbol::new('\u{22C5}', MathClass::Bin),
  "ast" => MathSymbol::new('\u{2217}', MathClass::Bin),
  "star" => MathSymbol::new('\u{22C6}', MathClass::Bin),
  "circ" => MathSymbol::new('\u{2218}', MathClass::Bin),
  "bullet" => MathSymbol::new('\u{2219}', MathClass::Bin),
  "diamond" => MathSymbol::new('\u{22C4}', MathClass::Bin),
  "setminus" => MathSymbol::new('\u{2216}', MathClass::Bin),
  "land" => MathSymbol::new('\u{2227}', MathClass::Bin),
  "lor" => MathSymbol::new('\u{2228}', MathClass::Bin),
  "cap" => MathSymbol::new('\u{2229}', MathClass::Bin),
  "cup" => MathSymbol::new('\u{222A}', MathClass::Bin),
  "sqcap" => MathSymbol::new('\u{2293}', MathClass::Bin),
  "sqcup" => MathSymbol::new('\u{2294}', MathClass::Bin),
  "uplus" => MathSymbol::new('\u{228E}', MathClass::Bin),
  "amalg" => MathSymbol::new('\u{2A3F}', MathClass::Bin),
  "wr" => MathSymbol::new('\u{2240}', MathClass::Bin),
  "oplus" => MathSymbol::new('\u{2295}', MathClass::Bin),
  "ominus" => MathSymbol::new('\u{2296}', MathClass::Bin),
  "otimes" => MathSymbol::new('\u{2297}', MathClass::Bin),
  "oslash" => MathSymbol::new('\u{2298}', MathClass::Bin),
  "odot" => MathSymbol::new('\u{2299}', MathClass::Bin),
  "boxplus" => MathSymbol::new('\u{229E}', MathClass::Bin),
  "boxminus" => MathSymbol::new('\u{229F}', MathClass::Bin),
  "boxtimes" => MathSymbol::new('\u{22A0}', MathClass::Bin),
  "boxdot" => MathSymbol::new('\u{22A1}', MathClass::Bin),
  "triangleleft" => MathSymbol::new('\u{25C1}', MathClass::Bin),
  "triangleright" => MathSymbol::new('\u{25B7}', MathClass::Bin),
  "bigtriangleup" => MathSymbol::new('\u{25B3}', MathClass::Bin),
  "bigtriangledown" => MathSymbol::new('\u{25BD}', MathClass::Bin),
  "dagger" => MathSymbol::new('\u{2020}', MathClass::Bin),
  "ddagger" => MathSymbol::new('\u{2021}', MathClass::Bin),
  "ltimes" => MathSymbol::new('\u{22C9}', MathClass::Bin),
  "rtimes" => MathSymbol::new('\u{22CA}', MathClass::Bin),
  "barwedge" => MathSymbol::new('\u{22BC}', MathClass::Bin),
  "veebar" => MathSymbol::new('\u{22BB}', MathClass::Bin),
  "intercal" => MathSymbol::new('\u{22BA}', MathClass::Bin),
  "Cap" => MathSymbol::new('\u{22D2}', MathClass::Bin),
  "Cup" => MathSymbol::new('\u{22D3}', MathClass::Bin),
  "middledot" => MathSymbol::new('\u{00B7}', MathClass::Bin),
  "smallblackcircle" => MathSymbol::new('\u{2022}', MathClass::Bin),
  "tieconcat" => MathSymbol::new('\u{2040}', MathClass::Bin),
  "fractionslash" => MathSymbol::new('\u{2044}', MathClass::Bin),
  "turnedampersand" => MathSymbol::new('\u{214B}', MathClass::Bin),
  "dotminus" => MathSymbol::new('\u{2238}', MathClass::Bin),
  "invertedlazys" => MathSymbol::new('\u{223E}', MathClass::Bin),
  "cupleftarrow" => MathSymbol::new('\u{228C}', MathClass::Bin),
  "cupdot" => MathSymbol::new('\u{228D}', MathClass::Bin),
  "circledcirc" => MathSymbol::new('\u{229A}', MathClass::Bin),
  "circledast" => MathSymbol::new('\u{229B}', MathClass::Bin),
  "circledequal" => MathSymbol::new('\u{229C}', MathClass::Bin),
  "circleddash" => MathSymbol::new('\u{229D}', MathClass::Bin),
  "barvee" => MathSymbol::new('\u{22BD}', MathClass::Bin),
  "divideontimes" => MathSymbol::new('\u{22C7}', MathClass::Bin),
  "leftthreetimes" => MathSymbol::new('\u{22CB}', MathClass::Bin),
  "rightthreetimes" => MathSymbol::new('\u{22CC}', MathClass::Bin),
  "curlyvee" => MathSymbol::new('\u{22CE}', MathClass::Bin),
  "curlywedge" => MathSymbol::new('\u{22CF}', MathClass::Bin),
  "projective" => MathSymbol::new('\u{2305}', MathClass::Bin),
  "perspective" => MathSymbol::new('\u{2306}', MathClass::Bin),
  "obar" => MathSymbol::new('\u{233D}', MathClass::Bin),
  "whitecircle" => MathSymbol::new('\u{25CB}', MathClass::Bin),
  "boxbar" => MathSymbol::new('\u{25EB}', MathClass::Bin),
  "veedot" => MathSymbol::new('\u{27C7}', MathClass::Bin),
  "wedgedot" => MathSymbol::new('\u{27D1}', MathClass::Bin),
  "lozengeminus" => MathSymbol::new('\u{27E0}', MathClass::Bin),
  "concavediamond" => MathSymbol::new('\u{27E1}', MathClass::Bin),
  "concavediamondtickleft" => MathSymbol::new('\u{27E2}', MathClass::Bin),
  "concavediamondtickright" => MathSymbol::new('\u{27E3}', MathClass::Bin),
  "whitesquaretickleft" => MathSymbol::new('\u{27E4}', MathClass::Bin),
  "whitesquaretickright" => MathSymbol::new('\u{27E5}', MathClass::Bin),
  "circlehbar" => MathSymbol::new('\u{29B5}', MathClass::Bin),
  "circledvert" => MathSymbol::new('\u{29B6}', MathClass::Bin),
  "circledparallel" => MathSymbol::new('\u{29B7}', MathClass::Bin),
  "obslash" => MathSymbol::new('\u{29B8}', MathClass::Bin),
  "operp" => MathSymbol::new('\u{29B9}', MathClass::Bin),
  "olessthan" => MathSymbol::new('\u{29C0}', MathClass::Bin),
  "ogreaterthan" => MathSymbol::new('\u{29C1}', MathClass::Bin),
  "boxslash" => MathSymbol::new('\u{29C4}', MathClass::Bin),
  "boxbackslash" => MathSymbol::new('\u{29C5}', MathClass::Bin),
  "boxast" => MathSymbol::new('\u{29C6}', MathClass::Bin),
  "boxcircle" => MathSymbol::new('\u{29C7}', MathClass::Bin),
  "boxbox" => MathSymbol::new('\u{29C8}', MathClass::Bin),
  "triangleserifs" => MathSymbol::new('\u{29CD}', MathClass::Bin),
  "hourglass" => MathSymbol::new('\u{29D6}', MathClass::Bin),
  "blackhourglass" => MathSymbol::new('\u{29D7}', MathClass::Bin),
  "shuffle" => MathSymbol::new('\u{29E2}', MathClass::Bin),
  "reversesolidus" => MathSymbol::new('\u{29F5}', MathClass::Bin),
  "overbarslash" => MathSymbol::new('\u{29F6}', MathClass::Bin),
  "backslashstroke" => MathSymbol::new('\u{29F7}', MathClass::Bin),
  "doubleplus" => MathSymbol::new('\u{29FA}', MathClass::Bin),
  "tripleplus" => MathSymbol::new('\u{29FB}', MathClass::Bin),
  "tplus" => MathSymbol::new('\u{29FE}', MathClass::Bin),
  "tminus" => MathSymbol::new('\u{29FF}', MathClass::Bin),
  "ringplus" => MathSymbol::new('\u{2A22}', MathClass::Bin),
  "plushat" => MathSymbol::new('\u{2A23}', MathClass::Bin),
  "simplus" => MathSymbol::new('\u{2A24}', MathClass::Bin),
  "plusdot" => MathSymbol::new('\u{2A25}', MathClass::Bin),
  "plussim" => MathSymbol::new('\u{2A26}', MathClass::Bin),
  "plussubtwo" => MathSymbol::new('\u{2A27}', MathClass::Bin),
  "plustrif" => MathSymbol::new('\u{2A28}', MathClass::Bin),
  "commaminus" => MathSymbol::new('\u{2A29}', MathClass::Bin),
  "minusdot" => MathSymbol::new('\u{2A2A}', MathClass::Bin),
  "minusfallingdots" => MathSymbol::new('\u{2A2B}', MathClass::Bin),
  "minusrisingdots" => MathSymbol::new('\u{2A2C}', MathClass::Bin),
  "opluslhrim" => MathSymbol::new('\u{2A2D}', MathClass::Bin),
  "oplusrhrim" => MathSymbol::new('\u{2A2E}', MathClass::Bin),
  "vectimes" => MathSymbol::new('\u{2A2F}', MathClass::Bin),
  "dottimes" => MathSymbol::new('\u{2A30}', MathClass::Bin),
  "timesbar" => MathSymbol::new('\u{2A31}', MathClass::Bin),
  "btimes" => MathSymbol::new('\u{2A32}', MathClass::Bin),
  "smashtimes" => MathSymbol::new('\u{2A33}', MathClass::Bin),
  "otimeslhrim" => MathSymbol::new('\u{2A34}', MathClass::Bin),
  "otimesrhrim" => MathSymbol::new('\u{2A35}', MathClass::Bin),
  "otimeshat" => MathSymbol::new('\u{2A36}', MathClass::Bin),
  "Otimes" => MathSymbol::new('\u{2A37}', MathClass::Bin),
  "odiv" => MathSymbol::new('\u{2A38}', MathClass::Bin),
  "triangleplus" => MathSymbol::new('\u{2A39}', MathClass::Bin),
  "triangleminus" => MathSymbol::new('\u{2A3A}', MathClass::Bin),
  "triangletimes" => MathSymbol::new('\u{2A3B}', MathClass::Bin),
  "intprod" => MathSymbol::new('\u{2A3C}', MathClass::Bin),
  "intprodright" => MathSymbol::new('\u{2A3D}', MathClass::Bin),
  "relcompose" => MathSymbol::new('\u{2A3E}', MathClass::Bin),
  "capdot" => MathSymbol::new('\u{2A40}', MathClass::Bin),
  "cupminus" => MathSymbol::new('\u{2A41}', MathClass::Bin),
  "barcup" => MathSymbol::new('\u{2A42}', MathClass::Bin),
  "barcap" => MathSymbol::new('\u{2A43}', MathClass::Bin),
  "capwedge" => MathSymbol::new('\u{2A44}', MathClass::Bin),
  "cupvee" => MathSymbol::new('\u{2A45}', MathClass::Bin),
  "cupovercap" => MathSymbol::new('\u{2A46}', MathClass::Bin),
  "capovercup" => MathSymbol::new('\u{2A47}', MathClass::Bin),
  "cupbarcap" => MathSymbol::new('\u{2A48}', MathClass::Bin),
  "capbarcup" => MathSymbol::new('\u{2A49}', MathClass::Bin),
  "twocups" => MathSymbol::new('\u{2A4A}', MathClass::Bin),
  "twocaps" => MathSymbol::new('\u{2A4B}', MathClass::Bin),
  "closedvarcup" => MathSymbol::new('\u{2A4C}', MathClass::Bin),
  "closedvarcap" => MathSymbol::new('\u{2A4D}', MathClass::Bin),
  "Sqcap" => MathSymbol::new('\u{2A4E}', MathClass::Bin),
  "Sqcup" => MathSymbol::new('\u{2A4F}', MathClass::Bin),
  "closedvarcupsmashprod" => MathSymbol::new('\u{2A50}', MathClass::Bin),
  "wedgeodot" => MathSymbol::new('\u{2A51}', MathClass::Bin),
  "veeodot" => MathSymbol::new('\u{2A52}', MathClass::Bin),
  "Wedge" => MathSymbol::new('\u{2A53}', MathClass::Bin),
  "Vee" => MathSymbol::new('\u{2A54}', MathClass::Bin),
  "wedgeonwedge" => MathSymbol::new('\u{2A55}', MathClass::Bin),
  "veeonvee" => MathSymbol::new('\u{2A56}', MathClass::Bin),
  "bigslopedvee" => MathSymbol::new('\u{2A57}', MathClass::Bin),
  "bigslopedwedge" => MathSymbol::new('\u{2A58}', MathClass::Bin),
  "wedgemidvert" => MathSymbol::new('\u{2A5A}', MathClass::Bin),
  "veemidvert" => MathSymbol::new('\u{2A5B}', MathClass::Bin),
  "midbarwedge" => MathSymbol::new('\u{2A5C}', MathClass::Bin),
  "midbarvee" => MathSymbol::new('\u{2A5D}', MathClass::Bin),
  "doublebarwedge" => MathSymbol::new('\u{2A5E}', MathClass::Bin),
  "wedgebar" => MathSymbol::new('\u{2A5F}', MathClass::Bin),
  "wedgedoublebar" => MathSymbol::new('\u{2A60}', MathClass::Bin),
  "smallveebar" => MathSymbol::new('\u{2A61}', MathClass::Bin),
  "doublebarvee" => MathSymbol::new('\u{2A62}', MathClass::Bin),
  "veedoublebar" => MathSymbol::new('\u{2A63}', MathClass::Bin),
  "domainantires" => MathSymbol::new('\u{2A64}', MathClass::Bin),
  "rangeantires" => MathSymbol::new('\u{2A65}', MathClass::Bin),
  "eqqplus" => MathSymbol::new('\u{2A71}', MathClass::Bin),
  "pluseqq" => MathSymbol::new('\u{2A72}', MathClass::Bin),
  "interleave" => MathSymbol::new('\u{2AF4}', MathClass::Bin),
  "nhVvert" => MathSymbol::new('\u{2AF5}', MathClass::Bin),
  "triplecolon" => MathSymbol::new('\u{2AF6}', MathClass::Bin),
  "tripleslash" => MathSymbol::new('\u{2AFB}', MathClass::Bin),
  "doubleslash" => MathSymbol::new('\u{2AFD}', MathClass::Bin),
  "whitevert" => MathSymbol::new('\u{2AFE}', MathClass::Bin),

  // 関係子
  "in" => MathSymbol::new('\u{2208}', MathClass::Rel),
  "notin" => MathSymbol::new('\u{2209}', MathClass::Rel),
  "ni" => MathSymbol::new('\u{220B}', MathClass::Rel),
  "notni" => MathSymbol::new('\u{220C}', MathClass::Rel),
  "propto" => MathSymbol::new('\u{221D}', MathClass::Rel),
  "mid" => MathSymbol::new('\u{2223}', MathClass::Rel),
  "nmid" => MathSymbol::new('\u{2224}', MathClass::Rel),
  "parallel" => MathSymbol::new('\u{2225}', MathClass::Rel),
  "notparallel" => MathSymbol::new('\u{2226}', MathClass::Rel),
  "backsim" => MathSymbol::new('\u{223D}', MathClass::Rel),
  "sim" => MathSymbol::new('\u{223C}', MathClass::Rel),
  "nsim" => MathSymbol::new('\u{2241}', MathClass::Rel),
  "simeq" => MathSymbol::new('\u{2243}', MathClass::Rel),
  "approx" => MathSymbol::new('\u{2248}', MathClass::Rel),
  "approxeq" => MathSymbol::new('\u{224A}', MathClass::Rel),
  "asymp" => MathSymbol::new('\u{224D}', MathClass::Rel),
  "cong" => MathSymbol::new('\u{2245}', MathClass::Rel),
  "ncong" => MathSymbol::new('\u{2247}', MathClass::Rel),
  "doteq" => MathSymbol::new('\u{2250}', MathClass::Rel),
  "triangleq" => MathSymbol::new('\u{225C}', MathClass::Rel),
  "neq" => MathSymbol::new('\u{2260}', MathClass::Rel),
  "equiv" => MathSymbol::new('\u{2261}', MathClass::Rel),
  "leq" => MathSymbol::new('\u{2264}', MathClass::Rel),
  "geq" => MathSymbol::new('\u{2265}', MathClass::Rel),
  "ll" => MathSymbol::new('\u{226A}', MathClass::Rel),
  "gg" => MathSymbol::new('\u{226B}', MathClass::Rel),
  "nless" => MathSymbol::new('\u{226E}', MathClass::Rel),
  "ngtr" => MathSymbol::new('\u{226F}', MathClass::Rel),
  "nleq" => MathSymbol::new('\u{2270}', MathClass::Rel),
  "ngeq" => MathSymbol::new('\u{2271}', MathClass::Rel),
  "lesssim" => MathSymbol::new('\u{2272}', MathClass::Rel),
  "gtrsim" => MathSymbol::new('\u{2273}', MathClass::Rel),
  "lessgtr" => MathSymbol::new('\u{2276}', MathClass::Rel),
  "gtrless" => MathSymbol::new('\u{2277}', MathClass::Rel),
  "prec" => MathSymbol::new('\u{227A}', MathClass::Rel),
  "succ" => MathSymbol::new('\u{227B}', MathClass::Rel),
  "preceq" => MathSymbol::new('\u{2AAF}', MathClass::Rel),
  "preccurlyeq" => MathSymbol::new('\u{227C}', MathClass::Rel),
  "succeq" => MathSymbol::new('\u{2AB0}', MathClass::Rel),
  "succcurlyeq" => MathSymbol::new('\u{227D}', MathClass::Rel),
  "nprec" => MathSymbol::new('\u{2280}', MathClass::Rel),
  "nsucc" => MathSymbol::new('\u{2281}', MathClass::Rel),
  "subset" => MathSymbol::new('\u{2282}', MathClass::Rel),
  "supset" => MathSymbol::new('\u{2283}', MathClass::Rel),
  "subseteq" => MathSymbol::new('\u{2286}', MathClass::Rel),
  "supseteq" => MathSymbol::new('\u{2287}', MathClass::Rel),
  "nsubseteq" => MathSymbol::new('\u{2288}', MathClass::Rel),
  "nsupseteq" => MathSymbol::new('\u{2289}', MathClass::Rel),
  "subsetneq" => MathSymbol::new('\u{228A}', MathClass::Rel),
  "supsetneq" => MathSymbol::new('\u{228B}', MathClass::Rel),
  "sqsubset" => MathSymbol::new('\u{228F}', MathClass::Rel),
  "sqsupset" => MathSymbol::new('\u{2290}', MathClass::Rel),
  "sqsubseteq" => MathSymbol::new('\u{2291}', MathClass::Rel),
  "sqsupseteq" => MathSymbol::new('\u{2292}', MathClass::Rel),
  "vdash" => MathSymbol::new('\u{22A2}', MathClass::Rel),
  "dashv" => MathSymbol::new('\u{22A3}', MathClass::Rel),
  "perp" => MathSymbol::new('\u{27C2}', MathClass::Rel),
  "models" => MathSymbol::new('\u{22A7}', MathClass::Rel),
  "vDash" => MathSymbol::new('\u{22A8}', MathClass::Rel),
  "nvdash" => MathSymbol::new('\u{22AC}', MathClass::Rel),

  // 矢印
  "leftarrow" => MathSymbol::new('\u{2190}', MathClass::Rel),
  "uparrow" => MathSymbol::new('\u{2191}', MathClass::Rel),
  "rightarrow" => MathSymbol::new('\u{2192}', MathClass::Rel),
  "downarrow" => MathSymbol::new('\u{2193}', MathClass::Rel),
  "leftrightarrow" => MathSymbol::new('\u{2194}', MathClass::Rel),
  "updownarrow" => MathSymbol::new('\u{2195}', MathClass::Rel),
  "nwarrow" => MathSymbol::new('\u{2196}', MathClass::Rel),
  "nearrow" => MathSymbol::new('\u{2197}', MathClass::Rel),
  "searrow" => MathSymbol::new('\u{2198}', MathClass::Rel),
  "swarrow" => MathSymbol::new('\u{2199}', MathClass::Rel),
  "nleftarrow" => MathSymbol::new('\u{219A}', MathClass::Rel),
  "nrightarrow" => MathSymbol::new('\u{219B}', MathClass::Rel),
  "twoheadleftarrow" => MathSymbol::new('\u{219E}', MathClass::Rel),
  "twoheadrightarrow" => MathSymbol::new('\u{21A0}', MathClass::Rel),
  "hookleftarrow" => MathSymbol::new('\u{21A9}', MathClass::Rel),
  "hookrightarrow" => MathSymbol::new('\u{21AA}', MathClass::Rel),
  "mapsto" => MathSymbol::new('\u{21A6}', MathClass::Rel),
  "nleftrightarrow" => MathSymbol::new('\u{21AE}', MathClass::Rel),
  "leftharpoonup" => MathSymbol::new('\u{21BC}', MathClass::Rel),
  "leftharpoondown" => MathSymbol::new('\u{21BD}', MathClass::Rel),
  "rightharpoonup" => MathSymbol::new('\u{21C0}', MathClass::Rel),
  "rightharpoondown" => MathSymbol::new('\u{21C1}', MathClass::Rel),
  "rightleftarrows" => MathSymbol::new('\u{21C4}', MathClass::Rel),
  "leftrightarrows" => MathSymbol::new('\u{21C6}', MathClass::Rel),
  "leftleftarrows" => MathSymbol::new('\u{21C7}', MathClass::Rel),
  "upuparrows" => MathSymbol::new('\u{21C8}', MathClass::Rel),
  "rightrightarrows" => MathSymbol::new('\u{21C9}', MathClass::Rel),
  "downdownarrows" => MathSymbol::new('\u{21CA}', MathClass::Rel),
  "rightleftharpoons" => MathSymbol::new('\u{21CC}', MathClass::Rel),
  "curvearrowleft" => MathSymbol::new('\u{21B6}', MathClass::Rel),
  "curvearrowright" => MathSymbol::new('\u{21B7}', MathClass::Rel),
  "circlearrowleft" => MathSymbol::new('\u{21BA}', MathClass::Rel),
  "circlearrowright" => MathSymbol::new('\u{21BB}', MathClass::Rel),
  "Leftarrow" => MathSymbol::new('\u{21D0}', MathClass::Rel),
  "Uparrow" => MathSymbol::new('\u{21D1}', MathClass::Rel),
  "Rightarrow" => MathSymbol::new('\u{21D2}', MathClass::Rel),
  "Downarrow" => MathSymbol::new('\u{21D3}', MathClass::Rel),
  "Leftrightarrow" => MathSymbol::new('\u{21D4}', MathClass::Rel),
  "Updownarrow" => MathSymbol::new('\u{21D5}', MathClass::Rel),
  "nLeftarrow" => MathSymbol::new('\u{21CD}', MathClass::Rel),
  "nLeftrightarrow" => MathSymbol::new('\u{21CE}', MathClass::Rel),
  "nRightarrow" => MathSymbol::new('\u{21CF}', MathClass::Rel),
  "longleftarrow" => MathSymbol::new('\u{27F5}', MathClass::Rel),
  "longrightarrow" => MathSymbol::new('\u{27F6}', MathClass::Rel),
  "longleftrightarrow" => MathSymbol::new('\u{27F7}', MathClass::Rel),
  "Longleftarrow" => MathSymbol::new('\u{27F8}', MathClass::Rel),
  "Longrightarrow" => MathSymbol::new('\u{27F9}', MathClass::Rel),
  "Longleftrightarrow" => MathSymbol::new('\u{27FA}', MathClass::Rel),
  "longmapsto" => MathSymbol::new('\u{27FC}', MathClass::Rel),
  "closure" => MathSymbol::new('\u{2050}', MathClass::Rel),
  "leftwavearrow" => MathSymbol::new('\u{219C}', MathClass::Rel),
  "rightwavearrow" => MathSymbol::new('\u{219D}', MathClass::Rel),
  "twoheaduparrow" => MathSymbol::new('\u{219F}', MathClass::Rel),
  "twoheaddownarrow" => MathSymbol::new('\u{21A1}', MathClass::Rel),
  "leftarrowtail" => MathSymbol::new('\u{21A2}', MathClass::Rel),
  "rightarrowtail" => MathSymbol::new('\u{21A3}', MathClass::Rel),
  "mapsfrom" => MathSymbol::new('\u{21A4}', MathClass::Rel),
  "mapsup" => MathSymbol::new('\u{21A5}', MathClass::Rel),
  "mapsdown" => MathSymbol::new('\u{21A7}', MathClass::Rel),
  "looparrowleft" => MathSymbol::new('\u{21AB}', MathClass::Rel),
  "looparrowright" => MathSymbol::new('\u{21AC}', MathClass::Rel),
  "leftrightsquigarrow" => MathSymbol::new('\u{21AD}', MathClass::Rel),
  "downzigzagarrow" => MathSymbol::new('\u{21AF}', MathClass::Rel),
  "Lsh" => MathSymbol::new('\u{21B0}', MathClass::Rel),
  "Rsh" => MathSymbol::new('\u{21B1}', MathClass::Rel),
  "Ldsh" => MathSymbol::new('\u{21B2}', MathClass::Rel),
  "Rdsh" => MathSymbol::new('\u{21B3}', MathClass::Rel),
  "upharpoonright" => MathSymbol::new('\u{21BE}', MathClass::Rel),
  "upharpoonleft" => MathSymbol::new('\u{21BF}', MathClass::Rel),
  "downharpoonright" => MathSymbol::new('\u{21C2}', MathClass::Rel),
  "downharpoonleft" => MathSymbol::new('\u{21C3}', MathClass::Rel),
  "updownarrows" => MathSymbol::new('\u{21C5}', MathClass::Rel),
  "leftrightharpoons" => MathSymbol::new('\u{21CB}', MathClass::Rel),
  "Nwarrow" => MathSymbol::new('\u{21D6}', MathClass::Rel),
  "Nearrow" => MathSymbol::new('\u{21D7}', MathClass::Rel),
  "Searrow" => MathSymbol::new('\u{21D8}', MathClass::Rel),
  "Swarrow" => MathSymbol::new('\u{21D9}', MathClass::Rel),
  "Lleftarrow" => MathSymbol::new('\u{21DA}', MathClass::Rel),
  "Rrightarrow" => MathSymbol::new('\u{21DB}', MathClass::Rel),
  "leftsquigarrow" => MathSymbol::new('\u{21DC}', MathClass::Rel),
  "rightsquigarrow" => MathSymbol::new('\u{21DD}', MathClass::Rel),
  "barleftarrow" => MathSymbol::new('\u{21E4}', MathClass::Rel),
  "rightarrowbar" => MathSymbol::new('\u{21E5}', MathClass::Rel),
  "circleonrightarrow" => MathSymbol::new('\u{21F4}', MathClass::Rel),
  "downuparrows" => MathSymbol::new('\u{21F5}', MathClass::Rel),
  "rightthreearrows" => MathSymbol::new('\u{21F6}', MathClass::Rel),
  "nvleftarrow" => MathSymbol::new('\u{21F7}', MathClass::Rel),
  "nvrightarrow" => MathSymbol::new('\u{21F8}', MathClass::Rel),
  "nvleftrightarrow" => MathSymbol::new('\u{21F9}', MathClass::Rel),
  "nVleftarrow" => MathSymbol::new('\u{21FA}', MathClass::Rel),
  "nVrightarrow" => MathSymbol::new('\u{21FB}', MathClass::Rel),
  "nVleftrightarrow" => MathSymbol::new('\u{21FC}', MathClass::Rel),
  "leftarrowtriangle" => MathSymbol::new('\u{21FD}', MathClass::Rel),
  "rightarrowtriangle" => MathSymbol::new('\u{21FE}', MathClass::Rel),
  "leftrightarrowtriangle" => MathSymbol::new('\u{21FF}', MathClass::Rel),
  "smallin" => MathSymbol::new('\u{220A}', MathClass::Rel),
  "smallni" => MathSymbol::new('\u{220D}', MathClass::Rel),
  "ratio" => MathSymbol::new('\u{2236}', MathClass::Rel),
  "doublecolon" => MathSymbol::new('\u{2237}', MathClass::Rel),
  "dashcolon" => MathSymbol::new('\u{2239}', MathClass::Rel),
  "dotsminusdots" => MathSymbol::new('\u{223A}', MathClass::Rel),
  "kernelcontraction" => MathSymbol::new('\u{223B}', MathClass::Rel),
  "eqsim" => MathSymbol::new('\u{2242}', MathClass::Rel),
  "nsimeq" => MathSymbol::new('\u{2244}', MathClass::Rel),
  "simneqq" => MathSymbol::new('\u{2246}', MathClass::Rel),
  "napprox" => MathSymbol::new('\u{2249}', MathClass::Rel),
  "approxident" => MathSymbol::new('\u{224B}', MathClass::Rel),
  "backcong" => MathSymbol::new('\u{224C}', MathClass::Rel),
  "Bumpeq" => MathSymbol::new('\u{224E}', MathClass::Rel),
  "bumpeq" => MathSymbol::new('\u{224F}', MathClass::Rel),
  "Doteq" => MathSymbol::new('\u{2251}', MathClass::Rel),
  "fallingdotseq" => MathSymbol::new('\u{2252}', MathClass::Rel),
  "risingdotseq" => MathSymbol::new('\u{2253}', MathClass::Rel),
  "coloneq" => MathSymbol::new('\u{2254}', MathClass::Rel),
  "eqcolon" => MathSymbol::new('\u{2255}', MathClass::Rel),
  "eqcirc" => MathSymbol::new('\u{2256}', MathClass::Rel),
  "circeq" => MathSymbol::new('\u{2257}', MathClass::Rel),
  "arceq" => MathSymbol::new('\u{2258}', MathClass::Rel),
  "wedgeeq" => MathSymbol::new('\u{2259}', MathClass::Rel),
  "veeeq" => MathSymbol::new('\u{225A}', MathClass::Rel),
  "stareq" => MathSymbol::new('\u{225B}', MathClass::Rel),
  "eqdef" => MathSymbol::new('\u{225D}', MathClass::Rel),
  "measuredby" => MathSymbol::new('\u{225E}', MathClass::Rel),
  "questioneq" => MathSymbol::new('\u{225F}', MathClass::Rel),
  "nequiv" => MathSymbol::new('\u{2262}', MathClass::Rel),
  "strictequiv" => MathSymbol::new('\u{2263}', MathClass::Rel),
  "leqq" => MathSymbol::new('\u{2266}', MathClass::Rel),
  "geqq" => MathSymbol::new('\u{2267}', MathClass::Rel),
  "lneqq" => MathSymbol::new('\u{2268}', MathClass::Rel),
  "gneqq" => MathSymbol::new('\u{2269}', MathClass::Rel),
  "between" => MathSymbol::new('\u{226C}', MathClass::Rel),
  "nasymp" => MathSymbol::new('\u{226D}', MathClass::Rel),
  "nlesssim" => MathSymbol::new('\u{2274}', MathClass::Rel),
  "ngtrsim" => MathSymbol::new('\u{2275}', MathClass::Rel),
  "nlessgtr" => MathSymbol::new('\u{2278}', MathClass::Rel),
  "ngtrless" => MathSymbol::new('\u{2279}', MathClass::Rel),
  "precsim" => MathSymbol::new('\u{227E}', MathClass::Rel),
  "succsim" => MathSymbol::new('\u{227F}', MathClass::Rel),
  "nsubset" => MathSymbol::new('\u{2284}', MathClass::Rel),
  "nsupset" => MathSymbol::new('\u{2285}', MathClass::Rel),
  "assert" => MathSymbol::new('\u{22A6}', MathClass::Rel),
  "Vdash" => MathSymbol::new('\u{22A9}', MathClass::Rel),
  "Vvdash" => MathSymbol::new('\u{22AA}', MathClass::Rel),
  "VDash" => MathSymbol::new('\u{22AB}', MathClass::Rel),
  "nvDash" => MathSymbol::new('\u{22AD}', MathClass::Rel),
  "nVdash" => MathSymbol::new('\u{22AE}', MathClass::Rel),
  "nVDash" => MathSymbol::new('\u{22AF}', MathClass::Rel),
  "precrel" => MathSymbol::new('\u{22B0}', MathClass::Rel),
  "succrel" => MathSymbol::new('\u{22B1}', MathClass::Rel),
  "vartriangleleft" => MathSymbol::new('\u{22B2}', MathClass::Rel),
  "vartriangleright" => MathSymbol::new('\u{22B3}', MathClass::Rel),
  "trianglelefteq" => MathSymbol::new('\u{22B4}', MathClass::Rel),
  "trianglerighteq" => MathSymbol::new('\u{22B5}', MathClass::Rel),
  "originalof" => MathSymbol::new('\u{22B6}', MathClass::Rel),
  "imageof" => MathSymbol::new('\u{22B7}', MathClass::Rel),
  "multimap" => MathSymbol::new('\u{22B8}', MathClass::Rel),
  "bowtie" => MathSymbol::new('\u{22C8}', MathClass::Rel),
  "backsimeq" => MathSymbol::new('\u{22CD}', MathClass::Rel),
  "Subset" => MathSymbol::new('\u{22D0}', MathClass::Rel),
  "Supset" => MathSymbol::new('\u{22D1}', MathClass::Rel),
  "pitchfork" => MathSymbol::new('\u{22D4}', MathClass::Rel),
  "equalparallel" => MathSymbol::new('\u{22D5}', MathClass::Rel),
  "lessdot" => MathSymbol::new('\u{22D6}', MathClass::Rel),
  "gtrdot" => MathSymbol::new('\u{22D7}', MathClass::Rel),
  "lll" => MathSymbol::new('\u{22D8}', MathClass::Rel),
  "ggg" => MathSymbol::new('\u{22D9}', MathClass::Rel),
  "lesseqgtr" => MathSymbol::new('\u{22DA}', MathClass::Rel),
  "gtreqless" => MathSymbol::new('\u{22DB}', MathClass::Rel),
  "eqless" => MathSymbol::new('\u{22DC}', MathClass::Rel),
  "eqgtr" => MathSymbol::new('\u{22DD}', MathClass::Rel),
  "curlyeqprec" => MathSymbol::new('\u{22DE}', MathClass::Rel),
  "curlyeqsucc" => MathSymbol::new('\u{22DF}', MathClass::Rel),
  "npreccurlyeq" => MathSymbol::new('\u{22E0}', MathClass::Rel),
  "nsucccurlyeq" => MathSymbol::new('\u{22E1}', MathClass::Rel),
  "nsqsubseteq" => MathSymbol::new('\u{22E2}', MathClass::Rel),
  "nsqsupseteq" => MathSymbol::new('\u{22E3}', MathClass::Rel),
  "sqsubsetneq" => MathSymbol::new('\u{22E4}', MathClass::Rel),
  "sqsupsetneq" => MathSymbol::new('\u{22E5}', MathClass::Rel),
  "lnsim" => MathSymbol::new('\u{22E6}', MathClass::Rel),
  "gnsim" => MathSymbol::new('\u{22E7}', MathClass::Rel),
  "precnsim" => MathSymbol::new('\u{22E8}', MathClass::Rel),
  "succnsim" => MathSymbol::new('\u{22E9}', MathClass::Rel),
  "ntriangleleft" => MathSymbol::new('\u{22EA}', MathClass::Rel),
  "ntriangleright" => MathSymbol::new('\u{22EB}', MathClass::Rel),
  "ntrianglelefteq" => MathSymbol::new('\u{22EC}', MathClass::Rel),
  "ntrianglerighteq" => MathSymbol::new('\u{22ED}', MathClass::Rel),
  "inlongstroke" => MathSymbol::new('\u{22F2}', MathClass::Rel),
  "inendbar" => MathSymbol::new('\u{22F3}', MathClass::Rel),
  "smallinendbar" => MathSymbol::new('\u{22F4}', MathClass::Rel),
  "indot" => MathSymbol::new('\u{22F5}', MathClass::Rel),
  "inoverbar" => MathSymbol::new('\u{22F6}', MathClass::Rel),
  "smallinoverbar" => MathSymbol::new('\u{22F7}', MathClass::Rel),
  "inunderbar" => MathSymbol::new('\u{22F8}', MathClass::Rel),
  "indoublestroke" => MathSymbol::new('\u{22F9}', MathClass::Rel),
  "nilongstroke" => MathSymbol::new('\u{22FA}', MathClass::Rel),
  "niendbar" => MathSymbol::new('\u{22FB}', MathClass::Rel),
  "smallniendbar" => MathSymbol::new('\u{22FC}', MathClass::Rel),
  "nioverbar" => MathSymbol::new('\u{22FD}', MathClass::Rel),
  "smallnioverbar" => MathSymbol::new('\u{22FE}', MathClass::Rel),
  "bagmember" => MathSymbol::new('\u{22FF}', MathClass::Rel),
  "frown" => MathSymbol::new('\u{2322}', MathClass::Rel),
  "smile" => MathSymbol::new('\u{2323}', MathClass::Rel),
  "slashbar" => MathSymbol::new('\u{233F}', MathClass::Rel),
  "vartriangle" => MathSymbol::new('\u{25B5}', MathClass::Rel),
  "backslashsubset" => MathSymbol::new('\u{27C8}', MathClass::Rel),
  "supsetslash" => MathSymbol::new('\u{27C9}', MathClass::Rel),
  "upin" => MathSymbol::new('\u{27D2}', MathClass::Rel),
  "pullback" => MathSymbol::new('\u{27D3}', MathClass::Rel),
  "pushout" => MathSymbol::new('\u{27D4}', MathClass::Rel),
  "DashVDash" => MathSymbol::new('\u{27DA}', MathClass::Rel),
  "dashVdash" => MathSymbol::new('\u{27DB}', MathClass::Rel),
  "leftmultimap" => MathSymbol::new('\u{27DC}', MathClass::Rel),
  "longlefttack" => MathSymbol::new('\u{27DD}', MathClass::Rel),
  "longrighttack" => MathSymbol::new('\u{27DE}', MathClass::Rel),
  "uptackcircle" => MathSymbol::new('\u{27DF}', MathClass::Rel),
  "UUparrow" => MathSymbol::new('\u{27F0}', MathClass::Rel),
  "DDownarrow" => MathSymbol::new('\u{27F1}', MathClass::Rel),
  "acwgapcirclearrow" => MathSymbol::new('\u{27F2}', MathClass::Rel),
  "cwgapcirclearrow" => MathSymbol::new('\u{27F3}', MathClass::Rel),
  "rightarrowonoplus" => MathSymbol::new('\u{27F4}', MathClass::Rel),
  "longmapsfrom" => MathSymbol::new('\u{27FB}', MathClass::Rel),
  "Longmapsfrom" => MathSymbol::new('\u{27FD}', MathClass::Rel),
  "Longmapsto" => MathSymbol::new('\u{27FE}', MathClass::Rel),
  "longrightsquigarrow" => MathSymbol::new('\u{27FF}', MathClass::Rel),
  "nvtwoheadrightarrow" => MathSymbol::new('\u{2900}', MathClass::Rel),
  "nVtwoheadrightarrow" => MathSymbol::new('\u{2901}', MathClass::Rel),
  "nvLeftarrow" => MathSymbol::new('\u{2902}', MathClass::Rel),
  "nvRightarrow" => MathSymbol::new('\u{2903}', MathClass::Rel),
  "nvLeftrightarrow" => MathSymbol::new('\u{2904}', MathClass::Rel),
  "twoheadmapsto" => MathSymbol::new('\u{2905}', MathClass::Rel),
  "Mapsfrom" => MathSymbol::new('\u{2906}', MathClass::Rel),
  "Mapsto" => MathSymbol::new('\u{2907}', MathClass::Rel),
  "downarrowbarred" => MathSymbol::new('\u{2908}', MathClass::Rel),
  "uparrowbarred" => MathSymbol::new('\u{2909}', MathClass::Rel),
  "Uuparrow" => MathSymbol::new('\u{290A}', MathClass::Rel),
  "Ddownarrow" => MathSymbol::new('\u{290B}', MathClass::Rel),
  "leftdoubledasharrow" => MathSymbol::new('\u{290C}', MathClass::Rel),
  "rightdoubledasharrow" => MathSymbol::new('\u{290D}', MathClass::Rel),
  "lefttripledasharrow" => MathSymbol::new('\u{290E}', MathClass::Rel),
  "righttripledasharrow" => MathSymbol::new('\u{290F}', MathClass::Rel),
  "twoheadrighttripledasharrow" => MathSymbol::new('\u{2910}', MathClass::Rel),
  "rightdotarrow" => MathSymbol::new('\u{2911}', MathClass::Rel),
  "baruparrow" => MathSymbol::new('\u{2912}', MathClass::Rel),
  "downarrowbar" => MathSymbol::new('\u{2913}', MathClass::Rel),
  "nvrightarrowtail" => MathSymbol::new('\u{2914}', MathClass::Rel),
  "nVrightarrowtail" => MathSymbol::new('\u{2915}', MathClass::Rel),
  "twoheadrightarrowtail" => MathSymbol::new('\u{2916}', MathClass::Rel),
  "nvtwoheadrightarrowtail" => MathSymbol::new('\u{2917}', MathClass::Rel),
  "nVtwoheadrightarrowtail" => MathSymbol::new('\u{2918}', MathClass::Rel),
  "lefttail" => MathSymbol::new('\u{2919}', MathClass::Rel),
  "righttail" => MathSymbol::new('\u{291A}', MathClass::Rel),
  "leftdoubletail" => MathSymbol::new('\u{291B}', MathClass::Rel),
  "rightdoubletail" => MathSymbol::new('\u{291C}', MathClass::Rel),
  "diamondleftarrow" => MathSymbol::new('\u{291D}', MathClass::Rel),
  "rightarrowdiamond" => MathSymbol::new('\u{291E}', MathClass::Rel),
  "diamondleftarrowbar" => MathSymbol::new('\u{291F}', MathClass::Rel),
  "barrightarrowdiamond" => MathSymbol::new('\u{2920}', MathClass::Rel),
  "nwsearrow" => MathSymbol::new('\u{2921}', MathClass::Rel),
  "neswarrow" => MathSymbol::new('\u{2922}', MathClass::Rel),
  "hooknwarrow" => MathSymbol::new('\u{2923}', MathClass::Rel),
  "hooknearrow" => MathSymbol::new('\u{2924}', MathClass::Rel),
  "hooksearrow" => MathSymbol::new('\u{2925}', MathClass::Rel),
  "hookswarrow" => MathSymbol::new('\u{2926}', MathClass::Rel),
  "nwnearrows" => MathSymbol::new('\u{2927}', MathClass::Rel),
  "nesearrows" => MathSymbol::new('\u{2928}', MathClass::Rel),
  "seswarrows" => MathSymbol::new('\u{2929}', MathClass::Rel),
  "swnwarrows" => MathSymbol::new('\u{292A}', MathClass::Rel),
  "rightcurvedarrow" => MathSymbol::new('\u{2933}', MathClass::Rel),
  "leftdowncurvedarrow" => MathSymbol::new('\u{2936}', MathClass::Rel),
  "rightdowncurvedarrow" => MathSymbol::new('\u{2937}', MathClass::Rel),
  "cwrightarcarrow" => MathSymbol::new('\u{2938}', MathClass::Rel),
  "acwleftarcarrow" => MathSymbol::new('\u{2939}', MathClass::Rel),
  "acwoverarcarrow" => MathSymbol::new('\u{293A}', MathClass::Rel),
  "acwunderarcarrow" => MathSymbol::new('\u{293B}', MathClass::Rel),
  "curvearrowrightminus" => MathSymbol::new('\u{293C}', MathClass::Rel),
  "curvearrowleftplus" => MathSymbol::new('\u{293D}', MathClass::Rel),
  "cwundercurvearrow" => MathSymbol::new('\u{293E}', MathClass::Rel),
  "acwundercurvearrow" => MathSymbol::new('\u{293F}', MathClass::Rel),
  "acwcirclearrow" => MathSymbol::new('\u{2940}', MathClass::Rel),
  "cwcirclearrow" => MathSymbol::new('\u{2941}', MathClass::Rel),
  "rightarrowshortleftarrow" => MathSymbol::new('\u{2942}', MathClass::Rel),
  "leftarrowshortrightarrow" => MathSymbol::new('\u{2943}', MathClass::Rel),
  "shortrightarrowleftarrow" => MathSymbol::new('\u{2944}', MathClass::Rel),
  "rightarrowplus" => MathSymbol::new('\u{2945}', MathClass::Rel),
  "leftarrowplus" => MathSymbol::new('\u{2946}', MathClass::Rel),
  "rightarrowx" => MathSymbol::new('\u{2947}', MathClass::Rel),
  "leftrightarrowcircle" => MathSymbol::new('\u{2948}', MathClass::Rel),
  "twoheaduparrowcircle" => MathSymbol::new('\u{2949}', MathClass::Rel),
  "leftrightharpoonupdown" => MathSymbol::new('\u{294A}', MathClass::Rel),
  "leftrightharpoondownup" => MathSymbol::new('\u{294B}', MathClass::Rel),
  "updownharpoonrightleft" => MathSymbol::new('\u{294C}', MathClass::Rel),
  "updownharpoonleftright" => MathSymbol::new('\u{294D}', MathClass::Rel),
  "leftrightharpoonupup" => MathSymbol::new('\u{294E}', MathClass::Rel),
  "updownharpoonrightright" => MathSymbol::new('\u{294F}', MathClass::Rel),
  "leftrightharpoondowndown" => MathSymbol::new('\u{2950}', MathClass::Rel),
  "updownharpoonleftleft" => MathSymbol::new('\u{2951}', MathClass::Rel),
  "barleftharpoonup" => MathSymbol::new('\u{2952}', MathClass::Rel),
  "rightharpoonupbar" => MathSymbol::new('\u{2953}', MathClass::Rel),
  "barupharpoonright" => MathSymbol::new('\u{2954}', MathClass::Rel),
  "downharpoonrightbar" => MathSymbol::new('\u{2955}', MathClass::Rel),
  "barleftharpoondown" => MathSymbol::new('\u{2956}', MathClass::Rel),
  "rightharpoondownbar" => MathSymbol::new('\u{2957}', MathClass::Rel),
  "barupharpoonleft" => MathSymbol::new('\u{2958}', MathClass::Rel),
  "downharpoonleftbar" => MathSymbol::new('\u{2959}', MathClass::Rel),
  "leftharpoonupbar" => MathSymbol::new('\u{295A}', MathClass::Rel),
  "barrightharpoonup" => MathSymbol::new('\u{295B}', MathClass::Rel),
  "upharpoonrightbar" => MathSymbol::new('\u{295C}', MathClass::Rel),
  "bardownharpoonright" => MathSymbol::new('\u{295D}', MathClass::Rel),
  "leftharpoondownbar" => MathSymbol::new('\u{295E}', MathClass::Rel),
  "barrightharpoondown" => MathSymbol::new('\u{295F}', MathClass::Rel),
  "upharpoonleftbar" => MathSymbol::new('\u{2960}', MathClass::Rel),
  "bardownharpoonleft" => MathSymbol::new('\u{2961}', MathClass::Rel),
  "leftharpoonsupdown" => MathSymbol::new('\u{2962}', MathClass::Rel),
  "upharpoonsleftright" => MathSymbol::new('\u{2963}', MathClass::Rel),
  "rightharpoonsupdown" => MathSymbol::new('\u{2964}', MathClass::Rel),
  "downharpoonsleftright" => MathSymbol::new('\u{2965}', MathClass::Rel),
  "leftrightharpoonsup" => MathSymbol::new('\u{2966}', MathClass::Rel),
  "leftrightharpoonsdown" => MathSymbol::new('\u{2967}', MathClass::Rel),
  "rightleftharpoonsup" => MathSymbol::new('\u{2968}', MathClass::Rel),
  "rightleftharpoonsdown" => MathSymbol::new('\u{2969}', MathClass::Rel),
  "leftharpoonupdash" => MathSymbol::new('\u{296A}', MathClass::Rel),
  "dashleftharpoondown" => MathSymbol::new('\u{296B}', MathClass::Rel),
  "rightharpoonupdash" => MathSymbol::new('\u{296C}', MathClass::Rel),
  "dashrightharpoondown" => MathSymbol::new('\u{296D}', MathClass::Rel),
  "updownharpoonsleftright" => MathSymbol::new('\u{296E}', MathClass::Rel),
  "downupharpoonsleftright" => MathSymbol::new('\u{296F}', MathClass::Rel),
  "rightimply" => MathSymbol::new('\u{2970}', MathClass::Rel),
  "equalrightarrow" => MathSymbol::new('\u{2971}', MathClass::Rel),
  "similarrightarrow" => MathSymbol::new('\u{2972}', MathClass::Rel),
  "leftarrowsimilar" => MathSymbol::new('\u{2973}', MathClass::Rel),
  "rightarrowsimilar" => MathSymbol::new('\u{2974}', MathClass::Rel),
  "rightarrowapprox" => MathSymbol::new('\u{2975}', MathClass::Rel),
  "lessleftarrow" => MathSymbol::new('\u{2976}', MathClass::Rel),
  "leftarrowless" => MathSymbol::new('\u{2977}', MathClass::Rel),
  "gtrrightarrow" => MathSymbol::new('\u{2978}', MathClass::Rel),
  "subsetrightarrow" => MathSymbol::new('\u{2979}', MathClass::Rel),
  "leftarrowsubset" => MathSymbol::new('\u{297A}', MathClass::Rel),
  "supsetleftarrow" => MathSymbol::new('\u{297B}', MathClass::Rel),
  "leftfishtail" => MathSymbol::new('\u{297C}', MathClass::Rel),
  "rightfishtail" => MathSymbol::new('\u{297D}', MathClass::Rel),
  "upfishtail" => MathSymbol::new('\u{297E}', MathClass::Rel),
  "downfishtail" => MathSymbol::new('\u{297F}', MathClass::Rel),
  "typecolon" => MathSymbol::new('\u{2982}', MathClass::Rel),
  "rtriltri" => MathSymbol::new('\u{29CE}', MathClass::Rel),
  "ltrivb" => MathSymbol::new('\u{29CF}', MathClass::Rel),
  "vbrtri" => MathSymbol::new('\u{29D0}', MathClass::Rel),
  "leftblackbowtie" => MathSymbol::new('\u{29D1}', MathClass::Rel),
  "rightblackbowtie" => MathSymbol::new('\u{29D2}', MathClass::Rel),
  "blackbowtie" => MathSymbol::new('\u{29D3}', MathClass::Rel),
  "leftblacktimes" => MathSymbol::new('\u{29D4}', MathClass::Rel),
  "rightblacktimes" => MathSymbol::new('\u{29D5}', MathClass::Rel),
  "dualmap" => MathSymbol::new('\u{29DF}', MathClass::Rel),
  "increasesas" => MathSymbol::new('\u{29E1}', MathClass::Rel),
  "eqslantparallel" => MathSymbol::new('\u{29E3}', MathClass::Rel),
  "simeqslantparallel" => MathSymbol::new('\u{29E4}', MathClass::Rel),
  "equivslantparallel" => MathSymbol::new('\u{29E5}', MathClass::Rel),
  "gleichstark" => MathSymbol::new('\u{29E6}', MathClass::Rel),
  "ruledelayed" => MathSymbol::new('\u{29F4}', MathClass::Rel),
  "veeonwedge" => MathSymbol::new('\u{2A59}', MathClass::Rel),
  "eqdot" => MathSymbol::new('\u{2A66}', MathClass::Rel),
  "dotequiv" => MathSymbol::new('\u{2A67}', MathClass::Rel),
  "equivVert" => MathSymbol::new('\u{2A68}', MathClass::Rel),
  "equivVvert" => MathSymbol::new('\u{2A69}', MathClass::Rel),
  "dotsim" => MathSymbol::new('\u{2A6A}', MathClass::Rel),
  "simrdots" => MathSymbol::new('\u{2A6B}', MathClass::Rel),
  "simminussim" => MathSymbol::new('\u{2A6C}', MathClass::Rel),
  "congdot" => MathSymbol::new('\u{2A6D}', MathClass::Rel),
  "asteq" => MathSymbol::new('\u{2A6E}', MathClass::Rel),
  "hatapprox" => MathSymbol::new('\u{2A6F}', MathClass::Rel),
  "approxeqq" => MathSymbol::new('\u{2A70}', MathClass::Rel),
  "eqqsim" => MathSymbol::new('\u{2A73}', MathClass::Rel),
  "doublecoloneq" => MathSymbol::new('\u{2A74}', MathClass::Rel),
  "eqeq" => MathSymbol::new('\u{2A75}', MathClass::Rel),
  "eqeqeq" => MathSymbol::new('\u{2A76}', MathClass::Rel),
  "ddotseq" => MathSymbol::new('\u{2A77}', MathClass::Rel),
  "equivDD" => MathSymbol::new('\u{2A78}', MathClass::Rel),
  "lesscircle" => MathSymbol::new('\u{2A79}', MathClass::Rel),
  "gtrcircle" => MathSymbol::new('\u{2A7A}', MathClass::Rel),
  "lessquestion" => MathSymbol::new('\u{2A7B}', MathClass::Rel),
  "gtrquestion" => MathSymbol::new('\u{2A7C}', MathClass::Rel),
  "leqslant" => MathSymbol::new('\u{2A7D}', MathClass::Rel),
  "geqslant" => MathSymbol::new('\u{2A7E}', MathClass::Rel),
  "lesdot" => MathSymbol::new('\u{2A7F}', MathClass::Rel),
  "gesdot" => MathSymbol::new('\u{2A80}', MathClass::Rel),
  "lesdoto" => MathSymbol::new('\u{2A81}', MathClass::Rel),
  "gesdoto" => MathSymbol::new('\u{2A82}', MathClass::Rel),
  "lesdotor" => MathSymbol::new('\u{2A83}', MathClass::Rel),
  "gesdotol" => MathSymbol::new('\u{2A84}', MathClass::Rel),
  "lessapprox" => MathSymbol::new('\u{2A85}', MathClass::Rel),
  "gtrapprox" => MathSymbol::new('\u{2A86}', MathClass::Rel),
  "lneq" => MathSymbol::new('\u{2A87}', MathClass::Rel),
  "gneq" => MathSymbol::new('\u{2A88}', MathClass::Rel),
  "lnapprox" => MathSymbol::new('\u{2A89}', MathClass::Rel),
  "gnapprox" => MathSymbol::new('\u{2A8A}', MathClass::Rel),
  "lesseqqgtr" => MathSymbol::new('\u{2A8B}', MathClass::Rel),
  "gtreqqless" => MathSymbol::new('\u{2A8C}', MathClass::Rel),
  "lsime" => MathSymbol::new('\u{2A8D}', MathClass::Rel),
  "gsime" => MathSymbol::new('\u{2A8E}', MathClass::Rel),
  "lsimg" => MathSymbol::new('\u{2A8F}', MathClass::Rel),
  "gsiml" => MathSymbol::new('\u{2A90}', MathClass::Rel),
  "lgE" => MathSymbol::new('\u{2A91}', MathClass::Rel),
  "glE" => MathSymbol::new('\u{2A92}', MathClass::Rel),
  "lesges" => MathSymbol::new('\u{2A93}', MathClass::Rel),
  "gesles" => MathSymbol::new('\u{2A94}', MathClass::Rel),
  "eqslantless" => MathSymbol::new('\u{2A95}', MathClass::Rel),
  "eqslantgtr" => MathSymbol::new('\u{2A96}', MathClass::Rel),
  "elsdot" => MathSymbol::new('\u{2A97}', MathClass::Rel),
  "egsdot" => MathSymbol::new('\u{2A98}', MathClass::Rel),
  "eqqless" => MathSymbol::new('\u{2A99}', MathClass::Rel),
  "eqqgtr" => MathSymbol::new('\u{2A9A}', MathClass::Rel),
  "eqqslantless" => MathSymbol::new('\u{2A9B}', MathClass::Rel),
  "eqqslantgtr" => MathSymbol::new('\u{2A9C}', MathClass::Rel),
  "simless" => MathSymbol::new('\u{2A9D}', MathClass::Rel),
  "simgtr" => MathSymbol::new('\u{2A9E}', MathClass::Rel),
  "simlE" => MathSymbol::new('\u{2A9F}', MathClass::Rel),
  "simgE" => MathSymbol::new('\u{2AA0}', MathClass::Rel),
  "Lt" => MathSymbol::new('\u{2AA1}', MathClass::Rel),
  "Gt" => MathSymbol::new('\u{2AA2}', MathClass::Rel),
  "partialmeetcontraction" => MathSymbol::new('\u{2AA3}', MathClass::Rel),
  "glj" => MathSymbol::new('\u{2AA4}', MathClass::Rel),
  "gla" => MathSymbol::new('\u{2AA5}', MathClass::Rel),
  "ltcc" => MathSymbol::new('\u{2AA6}', MathClass::Rel),
  "gtcc" => MathSymbol::new('\u{2AA7}', MathClass::Rel),
  "lescc" => MathSymbol::new('\u{2AA8}', MathClass::Rel),
  "gescc" => MathSymbol::new('\u{2AA9}', MathClass::Rel),
  "smaller" => MathSymbol::new('\u{2AAA}', MathClass::Rel),
  "larger" => MathSymbol::new('\u{2AAB}', MathClass::Rel),
  "smallereq" => MathSymbol::new('\u{2AAC}', MathClass::Rel),
  "largereq" => MathSymbol::new('\u{2AAD}', MathClass::Rel),
  "bumpeqq" => MathSymbol::new('\u{2AAE}', MathClass::Rel),
  "precneq" => MathSymbol::new('\u{2AB1}', MathClass::Rel),
  "succneq" => MathSymbol::new('\u{2AB2}', MathClass::Rel),
  "preceqq" => MathSymbol::new('\u{2AB3}', MathClass::Rel),
  "succeqq" => MathSymbol::new('\u{2AB4}', MathClass::Rel),
  "precneqq" => MathSymbol::new('\u{2AB5}', MathClass::Rel),
  "succneqq" => MathSymbol::new('\u{2AB6}', MathClass::Rel),
  "precapprox" => MathSymbol::new('\u{2AB7}', MathClass::Rel),
  "succapprox" => MathSymbol::new('\u{2AB8}', MathClass::Rel),
  "precnapprox" => MathSymbol::new('\u{2AB9}', MathClass::Rel),
  "succnapprox" => MathSymbol::new('\u{2ABA}', MathClass::Rel),
  "Prec" => MathSymbol::new('\u{2ABB}', MathClass::Rel),
  "Succ" => MathSymbol::new('\u{2ABC}', MathClass::Rel),
  "subsetdot" => MathSymbol::new('\u{2ABD}', MathClass::Rel),
  "supsetdot" => MathSymbol::new('\u{2ABE}', MathClass::Rel),
  "subsetplus" => MathSymbol::new('\u{2ABF}', MathClass::Rel),
  "supsetplus" => MathSymbol::new('\u{2AC0}', MathClass::Rel),
  "subsettimes" => MathSymbol::new('\u{2AC1}', MathClass::Rel),
  "supsettimes" => MathSymbol::new('\u{2AC2}', MathClass::Rel),
  "subseteqdot" => MathSymbol::new('\u{2AC3}', MathClass::Rel),
  "supseteqdot" => MathSymbol::new('\u{2AC4}', MathClass::Rel),
  "subseteqq" => MathSymbol::new('\u{2AC5}', MathClass::Rel),
  "supseteqq" => MathSymbol::new('\u{2AC6}', MathClass::Rel),
  "subsim" => MathSymbol::new('\u{2AC7}', MathClass::Rel),
  "supsim" => MathSymbol::new('\u{2AC8}', MathClass::Rel),
  "subsetapprox" => MathSymbol::new('\u{2AC9}', MathClass::Rel),
  "supsetapprox" => MathSymbol::new('\u{2ACA}', MathClass::Rel),
  "subsetneqq" => MathSymbol::new('\u{2ACB}', MathClass::Rel),
  "supsetneqq" => MathSymbol::new('\u{2ACC}', MathClass::Rel),
  "lsqhook" => MathSymbol::new('\u{2ACD}', MathClass::Rel),
  "rsqhook" => MathSymbol::new('\u{2ACE}', MathClass::Rel),
  "closedsubset" => MathSymbol::new('\u{2ACF}', MathClass::Rel),
  "closedsupset" => MathSymbol::new('\u{2AD0}', MathClass::Rel),
  "closedsubseteq" => MathSymbol::new('\u{2AD1}', MathClass::Rel),
  "closedsupseteq" => MathSymbol::new('\u{2AD2}', MathClass::Rel),
  "subsup" => MathSymbol::new('\u{2AD3}', MathClass::Rel),
  "supsub" => MathSymbol::new('\u{2AD4}', MathClass::Rel),
  "subsub" => MathSymbol::new('\u{2AD5}', MathClass::Rel),
  "supsup" => MathSymbol::new('\u{2AD6}', MathClass::Rel),
  "suphsub" => MathSymbol::new('\u{2AD7}', MathClass::Rel),
  "supdsub" => MathSymbol::new('\u{2AD8}', MathClass::Rel),
  "forkv" => MathSymbol::new('\u{2AD9}', MathClass::Rel),
  "topfork" => MathSymbol::new('\u{2ADA}', MathClass::Rel),
  "transversal" => MathSymbol::new('\u{2ADB}', MathClass::Rel),
  "forking" => MathSymbol::new('\u{2ADC}', MathClass::Rel),
  "nonforking" => MathSymbol::new('\u{2ADD}', MathClass::Rel),
  "shortlefttack" => MathSymbol::new('\u{2ADE}', MathClass::Rel),
  "shortdowntack" => MathSymbol::new('\u{2ADF}', MathClass::Rel),
  "shortuptack" => MathSymbol::new('\u{2AE0}', MathClass::Rel),
  "vDdash" => MathSymbol::new('\u{2AE2}', MathClass::Rel),
  "dashV" => MathSymbol::new('\u{2AE3}', MathClass::Rel),
  "Dashv" => MathSymbol::new('\u{2AE4}', MathClass::Rel),
  "DashV" => MathSymbol::new('\u{2AE5}', MathClass::Rel),
  "varVdash" => MathSymbol::new('\u{2AE6}', MathClass::Rel),
  "Barv" => MathSymbol::new('\u{2AE7}', MathClass::Rel),
  "vBar" => MathSymbol::new('\u{2AE8}', MathClass::Rel),
  "vBarv" => MathSymbol::new('\u{2AE9}', MathClass::Rel),
  "barV" => MathSymbol::new('\u{2AEA}', MathClass::Rel),
  "Vbar" => MathSymbol::new('\u{2AEB}', MathClass::Rel),
  "doublenot" => MathSymbol::new('\u{2AEC}', MathClass::Rel),
  "reverseddoublenot" => MathSymbol::new('\u{2AED}', MathClass::Rel),
  "revnmid" => MathSymbol::new('\u{2AEE}', MathClass::Rel),
  "cirmid" => MathSymbol::new('\u{2AEF}', MathClass::Rel),
  "midcir" => MathSymbol::new('\u{2AF0}', MathClass::Rel),
  "parallelstroke" => MathSymbol::new('\u{2AF2}', MathClass::Rel),
  "parsim" => MathSymbol::new('\u{2AF3}', MathClass::Rel),
  "lllnest" => MathSymbol::new('\u{2AF7}', MathClass::Rel),
  "gggnest" => MathSymbol::new('\u{2AF8}', MathClass::Rel),
  "leqqslant" => MathSymbol::new('\u{2AF9}', MathClass::Rel),
  "geqqslant" => MathSymbol::new('\u{2AFA}', MathClass::Rel),
  "circleonleftarrow" => MathSymbol::new('\u{2B30}', MathClass::Rel),
  "leftthreearrows" => MathSymbol::new('\u{2B31}', MathClass::Rel),
  "leftarrowonoplus" => MathSymbol::new('\u{2B32}', MathClass::Rel),
  "longleftsquigarrow" => MathSymbol::new('\u{2B33}', MathClass::Rel),
  "nvtwoheadleftarrow" => MathSymbol::new('\u{2B34}', MathClass::Rel),
  "nVtwoheadleftarrow" => MathSymbol::new('\u{2B35}', MathClass::Rel),
  "twoheadmapsfrom" => MathSymbol::new('\u{2B36}', MathClass::Rel),
  "twoheadlefttripledasharrow" => MathSymbol::new('\u{2B37}', MathClass::Rel),
  "leftdotarrow" => MathSymbol::new('\u{2B38}', MathClass::Rel),
  "nvleftarrowtail" => MathSymbol::new('\u{2B39}', MathClass::Rel),
  "nVleftarrowtail" => MathSymbol::new('\u{2B3A}', MathClass::Rel),
  "twoheadleftarrowtail" => MathSymbol::new('\u{2B3B}', MathClass::Rel),
  "nvtwoheadleftarrowtail" => MathSymbol::new('\u{2B3C}', MathClass::Rel),
  "nVtwoheadleftarrowtail" => MathSymbol::new('\u{2B3D}', MathClass::Rel),
  "leftarrowx" => MathSymbol::new('\u{2B3E}', MathClass::Rel),
  "leftcurvedarrow" => MathSymbol::new('\u{2B3F}', MathClass::Rel),
  "equalleftarrow" => MathSymbol::new('\u{2B40}', MathClass::Rel),
  "backsimleftarrow" => MathSymbol::new('\u{2B41}', MathClass::Rel),
  "leftarrowbackapprox" => MathSymbol::new('\u{2B42}', MathClass::Rel),
  "rightarrowgtr" => MathSymbol::new('\u{2B43}', MathClass::Rel),
  "rightarrowsupset" => MathSymbol::new('\u{2B44}', MathClass::Rel),
  "LLeftarrow" => MathSymbol::new('\u{2B45}', MathClass::Rel),
  "RRightarrow" => MathSymbol::new('\u{2B46}', MathClass::Rel),
  "backsimrightarrow" => MathSymbol::new('\u{2B47}', MathClass::Rel),
  "rightarrowbackapprox" => MathSymbol::new('\u{2B48}', MathClass::Rel),
  "similarleftarrow" => MathSymbol::new('\u{2B49}', MathClass::Rel),
  "leftarrowapprox" => MathSymbol::new('\u{2B4A}', MathClass::Rel),
  "leftarrowbacksim" => MathSymbol::new('\u{2B4B}', MathClass::Rel),
  "rightarrowbacksim" => MathSymbol::new('\u{2B4C}', MathClass::Rel),

  // 開き括弧・閉じ括弧
  "langle" => MathSymbol::new('\u{27E8}', MathClass::Open),
  "rangle" => MathSymbol::new('\u{27E9}', MathClass::Close),
  "lceil" => MathSymbol::new('\u{2308}', MathClass::Open),
  "rceil" => MathSymbol::new('\u{2309}', MathClass::Close),
  "lfloor" => MathSymbol::new('\u{230A}', MathClass::Open),
  "rfloor" => MathSymbol::new('\u{230B}', MathClass::Close),
  "ulcorner" => MathSymbol::new('\u{231C}', MathClass::Open),
  "urcorner" => MathSymbol::new('\u{231D}', MathClass::Close),
  "llcorner" => MathSymbol::new('\u{231E}', MathClass::Open),
  "lrcorner" => MathSymbol::new('\u{231F}', MathClass::Close),
  "lmoustache" => MathSymbol::new('\u{23B0}', MathClass::Open),
  "rmoustache" => MathSymbol::new('\u{23B1}', MathClass::Close),
  "ltortoise" => MathSymbol::new('\u{2772}', MathClass::Open),
  "rtortoise" => MathSymbol::new('\u{2773}', MathClass::Close),
  "lbag" => MathSymbol::new('\u{27C5}', MathClass::Open),
  "rbag" => MathSymbol::new('\u{27C6}', MathClass::Close),
  "lBrack" => MathSymbol::new('\u{27E6}', MathClass::Open),
  "rBrack" => MathSymbol::new('\u{27E7}', MathClass::Close),
  "lAngle" => MathSymbol::new('\u{27EA}', MathClass::Open),
  "rAngle" => MathSymbol::new('\u{27EB}', MathClass::Close),
  "lwhitetortoise" => MathSymbol::new('\u{27EC}', MathClass::Open),
  "rwhitetortoise" => MathSymbol::new('\u{27ED}', MathClass::Close),
  "lgroup" => MathSymbol::new('\u{27EE}', MathClass::Open),
  "rgroup" => MathSymbol::new('\u{27EF}', MathClass::Close),
  "lBrace" => MathSymbol::new('\u{2983}', MathClass::Open),
  "rBrace" => MathSymbol::new('\u{2984}', MathClass::Close),
  "lParen" => MathSymbol::new('\u{2985}', MathClass::Open),
  "rParen" => MathSymbol::new('\u{2986}', MathClass::Close),
  "llparenthesis" => MathSymbol::new('\u{2987}', MathClass::Open),
  "rrparenthesis" => MathSymbol::new('\u{2988}', MathClass::Close),
  "llangle" => MathSymbol::new('\u{2989}', MathClass::Open),
  "rrangle" => MathSymbol::new('\u{298A}', MathClass::Close),
  "lbrackubar" => MathSymbol::new('\u{298B}', MathClass::Open),
  "rbrackubar" => MathSymbol::new('\u{298C}', MathClass::Close),
  "lbrackultick" => MathSymbol::new('\u{298D}', MathClass::Open),
  "rbracklrtick" => MathSymbol::new('\u{298E}', MathClass::Close),
  "lbracklltick" => MathSymbol::new('\u{298F}', MathClass::Open),
  "rbrackurtick" => MathSymbol::new('\u{2990}', MathClass::Close),
  "langledot" => MathSymbol::new('\u{2991}', MathClass::Open),
  "rangledot" => MathSymbol::new('\u{2992}', MathClass::Close),
  "lparenless" => MathSymbol::new('\u{2993}', MathClass::Open),
  "rparengtr" => MathSymbol::new('\u{2994}', MathClass::Close),
  "Lparengtr" => MathSymbol::new('\u{2995}', MathClass::Open),
  "Rparenless" => MathSymbol::new('\u{2996}', MathClass::Close),
  "lblacktortoise" => MathSymbol::new('\u{2997}', MathClass::Open),
  "rblacktortoise" => MathSymbol::new('\u{2998}', MathClass::Close),
  "lvzigzag" => MathSymbol::new('\u{29D8}', MathClass::Open),
  "rvzigzag" => MathSymbol::new('\u{29D9}', MathClass::Close),
  "Lvzigzag" => MathSymbol::new('\u{29DA}', MathClass::Open),
  "Rvzigzag" => MathSymbol::new('\u{29DB}', MathClass::Close),
  "lcurvyangle" => MathSymbol::new('\u{29FC}', MathClass::Open),
  "rcurvyangle" => MathSymbol::new('\u{29FD}', MathClass::Close),
  "vert" => MathSymbol::new('\u{007C}', MathClass::Ord),
  "Vert" => MathSymbol::new('\u{2016}', MathClass::Ord),
};

/// 記号コマンド名から数式記号（文字 + 数式クラス）を引く。記号表に無ければ `None`
#[must_use]
pub(in crate::frontend::evaluator) fn lookup(name: &str) -> Option<MathSymbol> { return SYMBOLS.get(name).copied(); }

/// 記号表の全コマンド名（テストが数式の語彙との衝突を調べるのに使う。静的表から切り離せないテスト専用アクセサ）
#[cfg(test)]
pub(in crate::frontend::evaluator) fn names() -> impl Iterator<Item = &'static str> { return SYMBOLS.keys().copied(); }

#[cfg(test)]
mod tests {
  use std::collections::BTreeMap;

  use super::{SYMBOLS, lookup};
  use crate::{document::MathClass, frontend::evaluator::command::COMMANDS};

  /// `MathClass` は `Ord` を持たないので、`BTreeMap` のキーにするため序数へ写す
  fn class_ordinal(class: MathClass) -> u8 {
    return match class {
      MathClass::Ord => 0,
      MathClass::Op => 1,
      MathClass::Bin => 2,
      MathClass::Rel => 3,
      MathClass::Open => 4,
      MathClass::Close => 5,
      MathClass::Punct => 6,
    };
  }

  #[test]
  fn latex_spelled_names_point_to_the_unicode_math_character() {
    // LaTeX と同じ綴りの名前は unicode-math がその名前に対応づける字を指す
    assert_eq!(lookup("preceq").map(|s| return s.ch), Some('\u{2AAF}'));
    assert_eq!(lookup("succeq").map(|s| return s.ch), Some('\u{2AB0}'));
    assert_eq!(lookup("preccurlyeq").map(|s| return s.ch), Some('\u{227C}'));
    assert_eq!(lookup("succcurlyeq").map(|s| return s.ch), Some('\u{227D}'));
    assert_eq!(lookup("perp").map(|s| return s.ch), Some('\u{27C2}'));
    assert_eq!(lookup("models").map(|s| return s.ch), Some('\u{22A7}'));
    assert_eq!(lookup("vDash").map(|s| return s.ch), Some('\u{22A8}'));
    assert_eq!(lookup("blacktriangle").map(|s| return s.ch), Some('\u{25B4}'));
    assert_eq!(lookup("bigblacktriangleup").map(|s| return s.ch), Some('\u{25B2}'));
    assert_eq!(lookup("blacktriangledown").map(|s| return s.ch), Some('\u{25BE}'));
    assert_eq!(lookup("bigblacktriangledown").map(|s| return s.ch), Some('\u{25BC}'));
    assert_eq!(lookup("diagup").map(|s| return s.ch), Some('\u{27CB}'));
    assert_eq!(lookup("diagdown").map(|s| return s.ch), Some('\u{27CD}'));
    assert_eq!(lookup("epsilon").map(|s| return s.ch), Some('\u{03F5}'));
    assert_eq!(lookup("varepsilon").map(|s| return s.ch), Some('\u{03B5}'));
    assert_eq!(lookup("phi").map(|s| return s.ch), Some('\u{03D5}'));
    assert_eq!(lookup("varphi").map(|s| return s.ch), Some('\u{03C6}'));
  }

  #[test]
  fn added_relations_have_expected_char_and_class() {
    let rel = |name: &str| return lookup(name).map(|s| return (s.ch, s.class));
    assert_eq!(rel("leqslant"), Some(('\u{2A7D}', MathClass::Rel)));
    assert_eq!(rel("mapsfrom"), Some(('\u{21A4}', MathClass::Rel)));
    assert_eq!(rel("doublecolon"), Some(('\u{2237}', MathClass::Rel)));
    assert_eq!(rel("nsimeq"), Some(('\u{2244}', MathClass::Rel)));
    assert_eq!(rel("closedsubseteq"), Some(('\u{2AD1}', MathClass::Rel)));
    assert_eq!(rel("lefttripledasharrow"), Some(('\u{290E}', MathClass::Rel)));
    assert_eq!(rel("ratio"), Some(('\u{2236}', MathClass::Rel)));
  }

  #[test]
  fn added_binary_operators_have_expected_char_and_class() {
    let bin = |name: &str| return lookup(name).map(|s| return (s.ch, s.class));
    assert_eq!(bin("doubleplus"), Some(('\u{29FA}', MathClass::Bin)));
    assert_eq!(bin("circledast"), Some(('\u{229B}', MathClass::Bin)));
    assert_eq!(bin("middledot"), Some(('\u{00B7}', MathClass::Bin)));
    assert_eq!(bin("projective"), Some(('\u{2305}', MathClass::Bin)));
    assert_eq!(bin("smallblackcircle"), Some(('\u{2022}', MathClass::Bin)));
    assert_eq!(bin("whitecircle"), Some(('\u{25CB}', MathClass::Bin)));
    assert_eq!(bin("tplus"), Some(('\u{29FE}', MathClass::Bin)));
  }

  #[test]
  fn added_ordinary_symbols_have_expected_char_and_class() {
    let ord = |name: &str| return lookup(name).map(|s| return (s.ch, s.class));
    assert_eq!(ord("diameter"), Some(('\u{2300}', MathClass::Ord)));
    assert_eq!(ord("bigcirc"), Some(('\u{25EF}', MathClass::Ord)));
    assert_eq!(ord("differentiald"), Some(('\u{2146}', MathClass::Ord)));
    assert_eq!(ord("tinysquare"), Some(('\u{2B1E}', MathClass::Ord)));
    assert_eq!(ord("whitediamond"), Some(('\u{25C7}', MathClass::Ord)));
    assert_eq!(ord("sterling"), Some(('\u{00A3}', MathClass::Ord)));
    assert_eq!(ord("adots"), Some(('\u{22F0}', MathClass::Ord)), "vdots ddots と同じ Ord");
  }

  #[test]
  fn ascii_symbols_exist_only_where_direct_input_cannot_express_them() {
    // `\\` は改行なのでバックスラッシュの字は名前でしか書けず、直接の `:` は Rel なので区切りの `:` は名前が要る
    assert_eq!(lookup("backslash").map(|s| return (s.ch, s.class)), Some(('\\', MathClass::Ord)));
    assert_eq!(lookup("colon").map(|s| return (s.ch, s.class)), Some((':', MathClass::Punct)));
    assert!(lookup("lparen").is_none());
    assert!(lookup("equal").is_none());
  }

  #[test]
  fn added_operators_have_expected_char_and_class() {
    let op = |name: &str| return lookup(name).map(|s| return (s.ch, s.class));
    assert_eq!(op("iiiint"), Some(('\u{2A0C}', MathClass::Op)));
    assert_eq!(op("bigslash"), Some(('\u{29F8}', MathClass::Op)));
    assert_eq!(op("doublestrucksum"), Some(('\u{2140}', MathClass::Op)));
    assert_eq!(op("Join"), Some(('\u{2A1D}', MathClass::Op)));
  }

  #[test]
  fn every_open_symbol_has_its_closing_partner() {
    // typeset はクラスから開き・閉じ区切りを導いてインライン数式の分割点を決める。閉じの無い Open は以降の分割点を消す。
    // 対は Unicode の Bidi_Mirroring_Glyph（U+298D ⦍ ↔ U+2990 ⦐、U+298F ⦏ ↔ U+298E ⦎ 以外は次の符号位置）
    let partner = |ch: char| -> char {
      return match ch {
        '\u{298D}' => '\u{2990}',
        '\u{298F}' => '\u{298E}',
        _ => char::from_u32(u32::from(ch) + 1).expect("Open の字の次の符号位置は文字"),
      };
    };
    let closes: Vec<char> =
      SYMBOLS.values().filter(|s| return s.class == MathClass::Close).map(|s| return s.ch).collect();
    let opens: Vec<char> =
      SYMBOLS.values().filter(|s| return s.class == MathClass::Open).map(|s| return s.ch).collect();
    for open in &opens {
      assert!(closes.contains(&partner(*open)), "U+{:04X} の対の閉じ括弧が記号表に無い", u32::from(*open));
    }
    assert_eq!(opens.len(), closes.len());
  }

  #[test]
  fn added_delimiters_have_expected_char_and_class() {
    let sym = |name: &str| return lookup(name).map(|s| return (s.ch, s.class));
    assert_eq!(sym("lBrack"), Some(('\u{27E6}', MathClass::Open)));
    assert_eq!(sym("rBrack"), Some(('\u{27E7}', MathClass::Close)));
    assert_eq!(sym("lbrackultick"), Some(('\u{298D}', MathClass::Open)));
    assert_eq!(sym("rbrackurtick"), Some(('\u{2990}', MathClass::Close)));
    assert_eq!(sym("cuberoot"), Some(('\u{221B}', MathClass::Ord)), "対の無い根号は Ord");
    assert_eq!(sym("longdivision"), Some(('\u{27CC}', MathClass::Ord)), "対の無い長除法は Ord");
    assert_eq!(sym("Vvert"), Some(('\u{2980}', MathClass::Ord)), "unicode-math の fence は vert と同じ Ord");
  }

  #[test]
  fn one_name_per_character_and_class() {
    let mut seen = BTreeMap::new();
    for (name, symbol) in &SYMBOLS {
      let key = (symbol.ch, class_ordinal(symbol.class));
      if let Some(other) = seen.insert(key, *name) {
        panic!("同じ字・同じクラスに名前が 2 つあります: {other} と {name} (U+{:04X})", u32::from(symbol.ch));
      }
    }
  }

  #[test]
  fn representative_symbols_have_expected_class() {
    assert_eq!(lookup("alpha").map(|s| return s.class), Some(MathClass::Ord));
    assert_eq!(lookup("leq").map(|s| return s.class), Some(MathClass::Rel));
    assert_eq!(lookup("times").map(|s| return s.class), Some(MathClass::Bin));
    assert_eq!(lookup("sum").map(|s| return s.class), Some(MathClass::Op));
    assert_eq!(lookup("rightarrow").map(|s| return s.class), Some(MathClass::Rel));
    assert_eq!(lookup("langle").map(|s| return s.class), Some(MathClass::Open));
    assert_eq!(lookup("rangle").map(|s| return s.class), Some(MathClass::Close));
  }

  #[test]
  fn representative_symbols_map_to_expected_char() {
    assert_eq!(lookup("alpha").map(|s| return s.ch), Some('\u{03B1}'));
    assert_eq!(lookup("leq").map(|s| return s.ch), Some('\u{2264}'));
    assert_eq!(lookup("geq").map(|s| return s.ch), Some('\u{2265}'));
    assert_eq!(lookup("subseteq").map(|s| return s.ch), Some('\u{2286}'));
    assert_eq!(lookup("Rightarrow").map(|s| return s.ch), Some('\u{21D2}'));
  }

  #[test]
  fn lookup_returns_none_for_non_symbol_names() {
    // 機能コマンド（bold）・数式の構文コマンド（frac）・未知の名前の 3 種
    assert!(lookup("bold").is_none());
    assert!(lookup("frac").is_none());
    assert!(lookup("unknown").is_none());
  }

  #[test]
  fn no_key_collision_between_commands_and_symbols() {
    for key in SYMBOLS.keys() {
      assert!(!COMMANDS.contains_key(key), "COMMANDS と SYMBOLS にキーが重複しています: {key}");
    }
  }
}
