[package]
name = "font"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allsorts.workspace = true
font-types.workspace = true
harfrust.workspace = true
miette.workspace = true
rayon.workspace = true
read_config.workspace = true
read-fonts.workspace = true
thiserror.workspace = true
tracing.workspace = true
types.workspace = true

[lints]
workspace = true
