[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
name = "font"
version.workspace = true

[dependencies]
allsorts.workspace = true
harfbuzz_rs.workspace = true
pdf-writer.workspace = true
rayon.workspace = true
read_config_file = { path = "../read_config_file" }
stypes = { path = "../stypes" }
thiserror.workspace = true
ttf-parser.workspace = true

[lints]
workspace = true
