use phf::phf_map;

use crate::{
  evaluator::{EvalError, Evaluator, LayoutNode},
  parser::Command,
};

mod character;
mod control;
mod headline;

#[derive(Clone, Copy, Debug)]
enum CommandKind {
  Space,
  Part,
  Chapter,
  Section,
  Subsection,
  Paragraph,
  Subparagraph,
  UpperAlpha,
  UpperBeta,
  UpperGamma,
  UpperDelta,
  UpperEpsilon,
  UpperZeta,
  UpperEta,
  UpperTheta,
  UpperIota,
  UpperKappa,
  UpperLambda,
  UpperMu,
  UpperNu,
  UpperXi,
  UpperOmicron,
  UpperPi,
  UpperRho,
  UpperSigma,
  UpperTau,
  UpperUpsilon,
  UpperPhi,
  UpperChi,
  UpperPsi,
  UpperOmega,
  LowerAlpha,
  LowerBeta,
  LowerGamma,
  LowerDelta,
  LowerEpsilon,
  VarEpsilon,
  LowerZeta,
  LowerEta,
  LowerTheta,
  VarTheta,
  LowerIota,
  LowerKappa,
  VarKappa,
  LowerLambda,
  LowerMu,
  LowerNu,
  LowerXi,
  LowerOmicron,
  LowerPi,
  VarPi,
  LowerRho,
  VarRho,
  LowerSigma,
  VarSigma,
  LowerTau,
  LowerUpsilon,
  LowerPhi,
  LowerChi,
  LowerPsi,
  LowerOmega,
  ForAll,
  Complement,
  Partial,
  Exists,
  NotExists,
  Emptyset,
  Increment,
  Nabla,
  ElementOf,
  NotElementOf,
  ContainsAsMember,
  NotContainsAsMember,
  EndOfProof,
  Product,
  Coproduct,
  Summation,
  Minus,
  MinusOrPlus,
  DotPlus,
  Division,
  SquareRoot,
  ProportionalTo,
  Infinity,
  RightAngle,
  Angle,
  Parallel,
  NotParallel,
  LogicalAnd,
  LogicalOr,
  Intersection,
  Union,
  Integral,
  DoubleIntegral,
  TripleIntegral,
  ContourIntegral,
  SurfaceIntegral,
  VolumeIntegral,
  Therefore,
  Because,
  ReversedTilde,
  Undefined,
}

impl CommandKind {
  /// コマンドを実行し、対応するLayoutNodeを生成する
  ///
  /// # 引数
  ///
  /// * `command` - 実行するコマンド
  /// * `evaluator` - 評価器への可変参照
  ///
  /// # 戻り値
  ///
  /// 生成されたLayoutNode、またはエラー
  fn execute(self, command: Command, evaluator: &mut Evaluator) -> Result<LayoutNode, EvalError> {
    let style = evaluator.context.current_style;

    match self {
      Self::Space => control::space(&command),
      Self::Part => headline::part(&command, &mut evaluator.context),
      Self::Chapter => headline::chapter(&command, &mut evaluator.context),
      Self::Section => headline::section(&command, &mut evaluator.context),
      Self::Subsection => headline::subsection(&command, &mut evaluator.context),
      Self::Paragraph => headline::paragraph(&command, &mut evaluator.context),
      Self::Subparagraph => headline::subparagraph(&command, &mut evaluator.context),

      Self::UpperAlpha => character::upper_alpha(command, style),
      Self::UpperBeta => character::upper_beta(command, style),
      Self::UpperGamma => character::upper_gamma(command, style),
      Self::UpperDelta => character::upper_delta(command, style),
      Self::UpperEpsilon => character::upper_epsilon(command, style),
      Self::UpperZeta => character::upper_zeta(command, style),
      Self::UpperEta => character::upper_eta(command, style),
      Self::UpperTheta => character::upper_theta(command, style),
      Self::UpperIota => character::upper_iota(command, style),
      Self::UpperKappa => character::upper_kappa(command, style),
      Self::UpperLambda => character::upper_lambda(command, style),
      Self::UpperMu => character::upper_mu(command, style),
      Self::UpperNu => character::upper_nu(command, style),
      Self::UpperXi => character::upper_xi(command, style),
      Self::UpperOmicron => character::upper_omicron(command, style),
      Self::UpperPi => character::upper_pi(command, style),
      Self::UpperRho => character::upper_rho(command, style),
      Self::UpperSigma => character::upper_sigma(command, style),
      Self::UpperTau => character::upper_tau(command, style),
      Self::UpperUpsilon => character::upper_upsilon(command, style),
      Self::UpperPhi => character::upper_phi(command, style),
      Self::UpperChi => character::upper_chi(command, style),
      Self::UpperPsi => character::upper_psi(command, style),
      Self::UpperOmega => character::upper_omega(command, style),

      Self::LowerAlpha => character::lower_alpha(command, style),
      Self::LowerBeta => character::lower_beta(command, style),
      Self::LowerGamma => character::lower_gamma(command, style),
      Self::LowerDelta => character::lower_delta(command, style),
      Self::LowerEpsilon => character::lower_epsilon(command, style),
      Self::VarEpsilon => character::var_epsilon(command, style),
      Self::LowerZeta => character::lower_zeta(command, style),
      Self::LowerEta => character::lower_eta(command, style),
      Self::LowerTheta => character::lower_theta(command, style),
      Self::VarTheta => character::var_theta(command, style),
      Self::LowerIota => character::lower_iota(command, style),
      Self::LowerKappa => character::lower_kappa(command, style),
      Self::VarKappa => character::var_kappa(command, style),
      Self::LowerLambda => character::lower_lambda(command, style),
      Self::LowerMu => character::lower_mu(command, style),
      Self::LowerNu => character::lower_nu(command, style),
      Self::LowerXi => character::lower_xi(command, style),
      Self::LowerOmicron => character::lower_omicron(command, style),
      Self::LowerPi => character::lower_pi(command, style),
      Self::VarPi => character::var_pi(command, style),
      Self::LowerRho => character::lower_rho(command, style),
      Self::VarRho => character::var_rho(command, style),
      Self::LowerSigma => character::lower_sigma(command, style),
      Self::VarSigma => character::final_sigma(command, style),
      Self::LowerTau => character::lower_tau(command, style),
      Self::LowerUpsilon => character::lower_upsilon(command, style),
      Self::LowerPhi => character::lower_phi(command, style),
      Self::LowerChi => character::lower_chi(command, style),
      Self::LowerPsi => character::lower_psi(command, style),
      Self::LowerOmega => character::lower_omega(command, style),

      Self::ForAll => character::for_all(command, style),
      Self::Complement => character::complement(command, style),
      Self::Partial => character::partial(command, style),
      Self::Exists => character::exists(command, style),
      Self::NotExists => character::not_exists(command, style),
      Self::Emptyset => character::emptyset(command, style),
      Self::Increment => character::increment(command, style),
      Self::Nabla => character::nabla(command, style),
      Self::ElementOf => character::element_of(command, style),
      Self::NotElementOf => character::not_element_of(command, style),
      Self::ContainsAsMember => character::contains_as_member(command, style),
      Self::NotContainsAsMember => character::not_contains_as_member(command, style),
      Self::EndOfProof => character::end_of_proof(command, style),
      Self::Product => character::product(command, style),
      Self::Coproduct => character::coproduct(command, style),
      Self::Summation => character::summation(command, style),
      Self::Minus => character::minus(command, style),
      Self::MinusOrPlus => character::minus_or_plus(command, style),
      Self::DotPlus => character::dot_plus(command, style),
      Self::Division => character::division(command, style),
      Self::SquareRoot => character::square_root(command, style),
      Self::ProportionalTo => character::proportional_to(command, style),
      Self::Infinity => character::infinity(command, style),
      Self::RightAngle => character::right_angle(command, style),
      Self::Angle => character::angle(command, style),
      Self::Parallel => character::parallel(command, style),
      Self::NotParallel => character::not_parallel(command, style),
      Self::LogicalAnd => character::logical_and(command, style),
      Self::LogicalOr => character::logical_or(command, style),
      Self::Intersection => character::intersection(command, style),
      Self::Union => character::union(command, style),
      Self::Integral => character::integral(command, style),
      Self::DoubleIntegral => character::double_integral(command, style),
      Self::TripleIntegral => character::triple_integral(command, style),
      Self::ContourIntegral => character::contour_integral(command, style),
      Self::SurfaceIntegral => character::surface_integral(command, style),
      Self::VolumeIntegral => character::volume_integral(command, style),
      Self::Therefore => character::therefore(command, style),
      Self::Because => character::because(command, style),
      Self::ReversedTilde => character::reversed_tilde(command, style),

      Self::Undefined => Err(EvalError::UnknownCommand(command.name.to_string())),
    }
  }
}

static COMMAND_MAP: phf::Map<&'static str, CommandKind> = phf_map! {
  "space" => CommandKind::Space,

  "part" => CommandKind::Part,
  "chapter" => CommandKind::Chapter,
  "section" => CommandKind::Section,
  "subsection" => CommandKind::Subsection,
  "paragraph" => CommandKind::Paragraph,
  "subparagraph" => CommandKind::Subparagraph,

  "Alpha" => CommandKind::UpperAlpha,
  "Beta" => CommandKind::UpperBeta,
  "Gamma" => CommandKind::UpperGamma,
  "Delta" => CommandKind::UpperDelta,
  "Epsilon" => CommandKind::UpperEpsilon,
  "Zeta" => CommandKind::UpperZeta,
  "Eta" => CommandKind::UpperEta,
  "Theta" => CommandKind::UpperTheta,
  "Iota" => CommandKind::UpperIota,
  "Kappa" => CommandKind::UpperKappa,
  "Lambda" => CommandKind::UpperLambda,
  "Mu" => CommandKind::UpperMu,
  "Nu" => CommandKind::UpperNu,
  "Xi" => CommandKind::UpperXi,
  "Omicron" => CommandKind::UpperOmicron,
  "Pi" => CommandKind::UpperPi,
  "Rho" => CommandKind::UpperRho,
  "Sigma" => CommandKind::UpperSigma,
  "Tau" => CommandKind::UpperTau,
  "Upsilon" => CommandKind::UpperUpsilon,
  "Phi" => CommandKind::UpperPhi,
  "Chi" => CommandKind::UpperChi,
  "Psi" => CommandKind::UpperPsi,
  "Omega" => CommandKind::UpperOmega,
  "alpha" => CommandKind::LowerAlpha,
  "beta" => CommandKind::LowerBeta,
  "gamma" => CommandKind::LowerGamma,
  "delta" => CommandKind::LowerDelta,
  "epsilon" => CommandKind::LowerEpsilon,
  "varepsilon"=> CommandKind::VarEpsilon,
  "zeta" => CommandKind::LowerZeta,
  "eta" => CommandKind::LowerEta,
  "theta" => CommandKind::LowerTheta,
  "vartheta" => CommandKind::VarTheta,
  "iota" => CommandKind::LowerIota,
  "kappa" => CommandKind::LowerKappa,
  "varkappa" => CommandKind::VarKappa,
  "lambda" => CommandKind::LowerLambda,
  "mu" => CommandKind::LowerMu,
  "nu" => CommandKind::LowerNu,
  "xi" => CommandKind::LowerXi,
  "omicron" => CommandKind::LowerOmicron,
  "pi" => CommandKind::LowerPi,
  "varpi" => CommandKind::VarPi,
  "rho" => CommandKind::LowerRho,
  "varrho" => CommandKind::VarRho,
  "sigma" => CommandKind::LowerSigma,
  "varsigma" => CommandKind::VarSigma,
  "tau" => CommandKind::LowerTau,
  "upsilon" => CommandKind::LowerUpsilon,
  "phi" => CommandKind::LowerPhi,
  "chi" => CommandKind::LowerChi,
  "psi" => CommandKind::LowerPsi,
  "omega" => CommandKind::LowerOmega,

  "forall" => CommandKind::ForAll,
  "complement" => CommandKind::Complement,
  "partial" => CommandKind::Partial,
  "exists" => CommandKind::Exists,
  "notexists" => CommandKind::NotExists,
  "emptyset" => CommandKind::Emptyset,
  "increment" => CommandKind::Increment,
  "nabla" => CommandKind::Nabla,
  "in" => CommandKind::ElementOf,
  "notin" => CommandKind::NotElementOf,
  "ni" => CommandKind::ContainsAsMember,
  "notni" => CommandKind::NotContainsAsMember,
  "qed" => CommandKind::EndOfProof,
  "prod" => CommandKind::Product,
  "coprod" => CommandKind::Coproduct,
  "sum" => CommandKind::Summation,
  "minus" => CommandKind::Minus,
  "mp" => CommandKind::MinusOrPlus,
  "dotplus" => CommandKind::DotPlus,
  "surd" => CommandKind::SquareRoot,
  // division slash (distinct from \div)
  "slash" => CommandKind::Division,
  // proportions and infinity
  "propto" => CommandKind::ProportionalTo,
  "infty" => CommandKind::Infinity,
  // angles and parallels
  "angle" => CommandKind::Angle,
  "rightangle" => CommandKind::RightAngle,
  "parallel" => CommandKind::Parallel,
  "notparallel" => CommandKind::NotParallel,
  // logic
  "land" => CommandKind::LogicalAnd,
  "lor" => CommandKind::LogicalOr,
  // set operations
  "cap" => CommandKind::Intersection,
  "cup" => CommandKind::Union,
  // integrals
  "int" => CommandKind::Integral,
  "iint" => CommandKind::DoubleIntegral,
  "iiint" => CommandKind::TripleIntegral,
  "oint" => CommandKind::ContourIntegral,
  "oiint" => CommandKind::SurfaceIntegral,
  "oiiint" => CommandKind::VolumeIntegral,
  // reasoning symbols
  "therefore" => CommandKind::Therefore,
  "because" => CommandKind::Because,
  // relation-like
  "backsim" => CommandKind::ReversedTilde,
};

impl Evaluator {
  /// コマンドを評価し、対応するLayoutNodeを生成する
  ///
  /// # 引数
  ///
  /// * `command` - 評価するコマンド
  ///
  /// # 戻り値
  ///
  /// 生成されたLayoutNode、またはエラー
  ///
  /// # エラー
  ///
  /// 未知のコマンドやコマンド実行中のエラーが発生した場合
  pub(crate) fn evaluate_command(&mut self, command: Command) -> Result<LayoutNode, EvalError> {
    let command_kind = COMMAND_MAP.get(command.name.to_string().as_str()).copied().unwrap_or(CommandKind::Undefined);
    return command_kind.execute(command, self);
  }
}
