[package]
name = "layout"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
font.workspace = true
font-types.workspace = true
icu.workspace = true
lazy-regex.workspace = true
miette.workspace = true
parser.workspace = true
read-fonts.workspace = true
read_style.workspace = true
thiserror.workspace = true
types.workspace = true

[lints]
workspace = true
